# Il sentiero dei nidi di ragno {-}

## I {-}

Per arrivare fino in fondo al vicolo, i raggi del sole devono scendere diritti rasente le pareti fredde, tenute discoste a forza d’arcate che traversano la striscia di cielo azzurro carico.

Scendono diritti, i raggi del sole, giù per le finestre messe qua e là in disordine sui muri, e cespi di basilico e di origano piantati dentro pentole ai davanzali, e sottovesti stese appese a corde; fin giù al selciato, fatto a gradini e a ciottoli, con una cunetta in mezzo per l’orina dei muli.

Basta un grido di Pin, un grido per incominciare una canzone, a naso all’aria sulla soglia della bottega, o un grido cacciato prima che la mano di Pietromagro il ciabattino gli sia scesa tra capo e collo per picchiarlo, perché dai davanzali nasca un’eco di richiami e d’insulti.

– Pin! Già a quest’ora cominci ad angosciarci! Cantacene un po’ una, Pin! Pin, meschinetto, cosa ti fanno? Pin, muso di macacco! Ti si seccasse la voce in gola, una volta! Tu e quel rubagalline del tuo padrone! Tu e quel materasso di tua sorella!

Ma già Pin è in mezzo al carrugio, con le mani nelle tasche della giacca troppo da uomo per lui, che li guarda in faccia uno per uno senza ridere: – Di’ Celestino, sta’ un po’ zitto, bel vestito nuovo che hai. E di’, quel furto di stoffa ai Moli Nuovi, poi, non si sa ancora chi sia stato? Be’, che c’entra. Ciao Carolina, meno male quella volta. Sì, quella volta meno male tuo marito che non ha guardato sotto il letto. Anche tu, Pascà, m’han detto che è successo proprio al tuo paese. Sì, che Garibaldi ci ha portato il sapone e i tuoi paesani se lo son mangiato. Mangiasapone, Pascà, mondoboia, lo sapete quanto costa il sapone?

Pin ha una voce rauca da bambino vecchio: dice ogni battuta a bassa voce, serio, poi tutt’a un tratto sbotta in una risata in i che sembra un fischio e le lentiggini rosse e nere gli si affollano intorno agli occhi come un volo di vespe.

A canzonare Pin c’è sempre da rimettere: conosce tutti i fatti del carrugio e non si sa mai cosa va a tirar fuori. Mattina e sera sotto le finestre a sgolarsi in canzoni e in gridi, mentre nella bottega di Pietromagro la montagna di scarpe sfondate tra poco seppellisce il deschetto e trabocca in istrada.

– Pin! Macacco! Muso brutto! – gli grida qualche donna. – Mi risuolassi quelle ciabatte invece di starci ad angosciare tutto il giorno! È un mese che le avete lì nel mucchio. Lo dirò un po’ io al tuo padrone, quando lo metteranno fuori!

Pietromagro passa metà dell’anno in prigione, perché è nato disgraziato e quando c’è un furto nei dintorni finiscono sempre per mettere dentro lui. Torna e vede la montagna di scarpe sfondate e la bottega aperta senza dentro nessuno. Allora si siede al deschetto, piglia una scarpa, la gira, la rigira, la ributta nel mucchio; poi si prende la faccia pelosa tra le mani ossute, e sacramenta. Pin arriva fischiando e ancora non sa niente: ed ecco che si trova davanti Pietromagro con quelle mani già alte nell’aria e quelle pupille incorniciate di giallo e quella faccia nera di barba corta come pelo di cane. Grida, ma Pietromagro l’ha acciuffato e non lo molla; quando è stanco di picchiarlo lo lascia in bottega e s’infila all’osteria. Per quel giorno nessuno lo rivede.

La sera, ogni due giorni, dalla sorella di Pin viene il marinaio tedesco. Pin lo aspetta nel carrugio ogni volta mentre sale, per chiedergli una sigaretta; i primi tempi era generoso e ne regalava anche tre, quattro per volta. Prendere in giro il marinaio tedesco è facile perché lui non capisce e guarda con quella faccia quagliata, senza contorno, rasa fin sulle tempie. Poi, quando se n’è andato, gli si possono fare gli sberleffi dietro, sicuri che non si volta; è ridicolo visto di dietro, con quei due nastri neri che gli scendono dal berretto marinaio fino al sedere lasciato scoperto dal giubbetto corto, un sedere carnoso, da donna, con una grossa pistola tedesca poggiata sopra.

– Ruffiano... Ruffiano... – dice la gente a Pin dalle finestre, sottovoce perché con quei tipi è meglio non scherzare.

– Cornuti... Cornuti... – risponde Pin facendo loro il verso e ingozzandosi di fumo gola e naso, fumo ancora aspro e ruvido contro la sua gola di bambino, ma di cui bisogna ingozzarsi fino a farsi lagrimare gli occhi e tossire con rabbia, non si sa bene il perché. Poi, con la sigaretta in bocca, andare all’osteria e dire: – Mondoboia, chi mi paga un bicchiere gli dico una cosa che poi mi dice grazie.

All’osteria ci sono sempre gli stessi, tutt’il giorno, da anni, a gomiti sui tavoli e menti sui pugni che guardano le mosche sull’incerato e l’ombra viola in fondo ai bicchieri.

– Che c’è, – dice Miscèl il Francese. – Tua sorella ha ribassato i prezzi?

Gli altri ridono e picchiano pugni sullo zinco: – Te la sei presa questa volta, Pin, la risposta!

Pin è lì che lo guarda di sotto in su attraverso la frangia di capelli spinosi che gli mangia la fronte.

– Mondoboia, proprio come pensavo io. Guardate un poco, pensa sempre a mia sorella. Vi dico, non smette mai di pensarci: s’è innamorato. Di mia sorella s’è innamorato, che coraggio...

Gli altri ridono a gola spiegata e lo scappellottano e gli versano un bicchiere. Il vino non piace a Pin: è aspro contro la gola e arriccia la pelle e mette addosso una smania di ridere, gridare ed essere cattivi. Pure lo beve, tracanna bicchieri tutto d’un fiato come inghiotte fumo, come alla notte spia con schifo la sorella sul letto insieme a uomini nudi, e il vederla è come una carezza ruvida, sotto la pelle, un gusto aspro, come tutte le cose degli uomini; fumo, vino, donne.

– Canta, Pin, – gli dicono. Pin canta bene, serio, impettito, con quella voce di bambino rauco. Canta Le quattro stagioni.



Ma quando penso all’avvenir

della mia libertà perduta

vorrei baciarla e poi morir

mentre lei dorme... all’insaputa...



Gli uomini ascoltano in silenzio, a occhi bassi come fosse un inno di chiesa. Tutti sono stati in prigione: chi non è stato mai in prigione non è un uomo. E la vecchia canzone da galeotti è piena di quello sconforto che viene nelle ossa alla sera, in prigione, quando i secondini passano a battere le grate con una spranga di ferro, e a poco a poco tutti i litigi, le imprecazioni si quetano, e rimane solo una voce che canta quella canzone, come ora Pin, e nessuno gli grida di smettere.



Amo la notte ascoltar

il grido della sentinella.

Amo la luna al suo passar

quando illumina la mia cella.

Pin proprio in prigione non è mai stato: quella volta che volevano portarlo ai discoli, è scappato. Ogni tanto lo acchiappano le guardie municipali, per qualche scorribanda per le tettoie del mercato della verdura, ma lui fa impazzire tutto il corpo di guardia dagli strilli e dai pianti finché non lo liberano. Ma nella guardina dei vigili un po’ c’è stato rinchiuso, e sa cosa vuol dire, e perciò canta bene, con sentimento.

Pin sa tutte quelle vecchie canzoni che gli uomini dell’osteria gli hanno insegnato, canzoni che raccontano fatti di sangue; quella che fa: Torna Caserio... e quella di Peppino che uccide il tenente. Poi, a un tratto, quando tutti sono tristi e guardano nel viola dei bicchieri e scatarrano, Pin fa una piroetta in mezzo al fumo dell’osteria, e intona a squarciagola:

– E le toccai i capelli – e lei disse non son quelli – vai più giù che son più belli, – amor se mi vuoi bene – più giù devi toccar.

Allora gli uomini dànno pugni sullo zinco e la serva mette in salvo i bicchieri, e gridano «hiuù» e battono il tempo con le mani. E le donne che sono nell’osteria, vecchie ubriacone con la faccia rossa, come la Bersagliera, ballonzolano accennando un passo di danza. E Pin, col sangue alla testa, e una rabbia che gli fa stringere i denti, si sgola nella canzonaccia fino a lasciarci l’anima:

– E le toccai il nasino – e lei disse brutto cretino – vai più giù che c’è un giardino.

E tutti gli altri, battendo il tempo con le mani alla vecchia Bersagliera che ballonzola, fanno il coro:

– Amor se mi vuoi bene – più giù devi toccar.

Quel giorno il marinaio tedesco veniva su di cattivo umore. Amburgo, il suo paese, era mangiato dalle bombe ogni giorno, e lui aspettava notizie ogni giorno di sua moglie, dei suoi bambini. Aveva un temperamento affettivo, il tedesco, un temperamento da meridionale trapiantato in un uomo del mare del Nord. S’era riempito la casa di figlioli, e adesso, spinto lontano dalla guerra, cercava di smaltire la sua carica di calore umano affezionandosi a prostitute dei paesi occupati.

– Niente sigarette avere, – dice a Pin che gli è venuto incontro a dargli il gutentag. Pin comincia a smicciarlo di traverso.

– Ben, camerata, da queste parti anche quest’oggi, è la nostalgia, eh?

Ora è il tedesco a smicciare Pin; non capisce.

– Vieni da trovare mia sorella, per caso? – fa Pin, con noncuranza.

E il tedesco: – Sorella non in casa?

– Ma come, non lo sai? – Pin ha una faccia falsa che sembra allevato dai preti. – Non lo sai che l’hanno portata all’ospedale, poveretta! Malattia brutta, ma pare che adesso la curino, se presa in tempo. Certo che lei ce l’aveva già da un po’... In ospedale, ci pensi, poveretta!

La faccia del tedesco sembra latte quagliato: balbetta e suda: – O-spe-da-le? Ma-la-ttia? – Da una finestra dell’ammezzato s’affaccia il busto d’una giovane con la faccia equina e i capelli da negra.

– Non dargli retta, Frick, non dargli retta a quel senza vergogna, – grida. – Questa poi me la paghi, muso di macacco, manca poco e mi rovini! Vieni su, Frick, non dargli retta che scherzava, il diavolo che se lo porti!

Pin le fa uno sberleffo. – Te la sei presa una sudata fredda, camerata! – fa al tedesco e scantona per un vicolo.

A volte il fare uno scherzo cattivo lascia un gusto amaro, e Pin si trova solo a girare nei vicoli, con tutti che gli gridano improperi e lo cacciano via. Si avrebbe voglia d’andare con una banda di compagni, allora, compagni cui spiegare il posto dove fanno il nido i ragni, o con cui fare battaglie con le canne, nel fossato. Ma i ragazzi non vogliono bene a Pin: è l’amico dei grandi, Pin, sa dire ai grandi cose che li fanno ridere e arrabbiare, non come loro che non capiscono nulla quando i grandi parlano. Pin alle volte vorrebbe mettersi coi ragazzi della sua età, chiedere che lo lascino giocare a testa e pila, e che gli spieghino la via per un sotterraneo che arriva fino in piazza Mercato. Ma i ragazzi lo lasciano a parte, e a un certo punto si mettono a picchiarlo; perché Pin ha due braccine smilze smilze ed è il più debole di tutti. Da Pin vanno alle volte a chiedere spiegazioni su cose che succedono tra le donne e gli uomini; ma Pin comincia a canzonarli gridando per il carrugio e le madri richiamano i ragazzi: – Costanzo! Giacomino! Quante volte te l’ho detto che non devi andare con quel ragazzo così maleducato!

Le madri hanno ragione: Pin non sa che raccontare storie d’uomini e donne nei letti e di uomini ammazzati o messi in prigione, storie insegnategli dai grandi, specie di fiabe che i grandi si raccontano tra loro e che pure sarebbe bello stare a sentire se Pin non le intercalasse di canzonature e di cose che non si capiscono da indovinare.

E a Pin non resta che rifugiarsi nel mondo dei grandi, dei grandi che pure gli voltano la schiena, dei grandi che pure sono incomprensibili e distanti per lui come per gli altri ragazzi, ma che sono più facili da prendere in giro, con quella voglia delle donne e quella paura dei carabinieri, finché non si stancano e cominciano a scapaccionarlo.

Ora Pin entrerà nell’osteria fumosa e viola, e dirà cose oscene, improperi mai uditi a quegli uomini fino a farli imbestialire e a farsi battere, e canterà canzoni commoventi, struggendosi fino a piangere e a farli piangere, e inventerà scherzi e smorfie così nuove da ubriacarsi di risate, tutto per smaltire la nebbia di solitudine che gli si condensa nel petto le sere come quella.

Ma nell’osteria gli uomini sono un muro di schiene che non s’apre per lui; e c’è un uomo nuovo in mezzo a loro, tutto magro e serio. Gli uomini smicciano Pin che entra, poi smicciano lo sconosciuto e dicono qualche parola. Pin vede che tira aria diversa; ragione di più per farsi avanti a mani in tasca e dire: – Mondoboia, la faccia che ha fatto il tedesco dovevate vedere.

Gli uomini non rispondono con le solite uscite. Si voltano piano, a uno a uno. Miscèl Francese prima lo smiccia come se non lo avesse mai visto, poi dice, lento: – Sei una sporca carogna di ruffiano.

Il volo di vespe sulla faccia di Pin ha un guizzo subito spento, poi Pin parla calmo, ma con gli occhi piccoli: – Poi mi dici perché.

Il Giraffa volta un po’ il collo verso di lui e fa: – Vai via, noi con chi se la fa coi tedeschi non abbiamo nulla da spartire.

– Va a finire, – dice Gian l’Autista, – che diventerete pezzi grossi del fascio, tu e tua sorella, con le vostre relazioni.

Pin cerca di fare la faccia di quando li prende in giro.

– Poi mi spiegate il significato, – dice. – Io col fascio non ci ho mai avuto niente da spartire, nemmeno coi balilla, e mia sorella va con chi le pare e non dà fastidio a nessuno.

Miscèl si gratta un po’ la faccia: – Quando viene il giorno che cambia tutto, mi capisci? tua sorella la facciamo girare rasata e nuda come una gallina spennata... E per te... per te studiamo un servizio che non te lo sogni neppure.

Pin non si scompone ma si vede che dentro ci soffre e si morde le labbra: – Quando viene il giorno che diventate più furbi, – dice, – vi spiegherò come stanno le cose. Primo, che io con mia sorella non sappiamo niente l’uno dell’altro e il ruffiano lo andate a fare voi se ne avete voglia. Secondo, che mia sorella non va coi tedeschi perché tiene coi tedeschi, ma perché è internazionale come la crocerossa e alla maniera che va con loro poi andrà con gl’inglesi, i negri e tutti i sacramenti che verranno dopo –. (Questi son tutti discorsi che Pin ha imparato ascoltando i grandi, magari quelli stessi che ora parlano con lui. Perché ora tocca a lui spiegarlo a loro?) – Terzo, che io col tedesco tutto quel che ho fatto è stato scroccargli delle gran sigarette, e in cambio gli ho fatto degli scherzi come quello di quest’oggi che ormai m’avete fatto girar l’anima e non ve lo racconto più.

Ma il tentativo di sviare il discorso non attacca. Gian l’Autista dice: – Tempo di scherzare! Io sono stato in Croazia e lì bastava che uno scemo di tedesco andasse per donne in un paese che non se ne trovava più manco il cadavere.

Miscèl dice: – Un giorno o l’altro te lo facciamo trovare in un tombino, il tuo tedesco.

Lo sconosciuto che è stato tutto il tempo zitto, senz’approvare né sorridere, lo tira un po’ per una manica: – Non è il caso di parlar di questo adesso. Ricordatevi quel che v’ho detto.

Gli altri annuiscono e guardano ancora Pin. Che cosa possono volere da lui?

– Di’, – fa Miscèl, – hai visto che pistola ha il marinaio?

– Un boia di pistola, ha, – risponde Pin.

– Ben, – fa Miscèl, – tu ci porterai quella pistola.

– E come faccio? – fa Pin.

– T’arrangi.

– Ma come faccio se la porta sempre appiccicata al sedere. Pigliatela voi.

– Ben, dico: a un certo punto non se li toglie i pantaloni? E allora si toglie anche la pistola, sta’ sicuro. Tu vai e gliela prendi. T’arrangi.

– Se voglio.

– Senti, – fa il Giraffa, – non stiamo qui a scherzare. Se vuoi essere dei nostri ora sai cosa devi fare; se no...

– Se no?

– Se no... Lo sai che cos’è un gap?

L’uomo sconosciuto dà una gomitata al Giraffa e scuote il capo: sembra sia scontento del modo di fare degli altri.

Per Pin le parole nuove hanno sempre un alone di mistero, come se alludessero a qualche fatto oscuro e proibito. Un gap? Che cosa sarà un gap?

– Sì che lo so cos’è, – dice.

– Cos’è? – fa Giraffa.

– È quello che in... te e tutta la tua famiglia.

Ma gli uomini non gli dànno retta. Lo sconosciuto ha fatto loro cenno che avvicinino la testa e parla loro a bassa voce, e sembra che li sgridi di qualcosa, e gli uomini fanno cenno che ha ragione.

Pin è fuori di tutto questo. Ora se ne andrà senza dir niente, e di quella storia della pistola è meglio non se ne parli più, era una cosa senz’importanza, forse gli uomini l’hanno già dimenticata.

Ma Pin è appena alla porta quando il Francese alza la testa e dice: – Pin, allora per quella storia siamo intesi.

Pin vorrebbe riprincipiare a far lo scemo, ma improvvisamente si sente bambino in mezzo ai grandi e rimane con la mano sullo stipite della porta.

– Se no non ti far più vedere, – dice il Francese.

Pin ora è nel carrugio. È sera e alle finestre s’accendono i lumi. Lontano, nel torrente, cominciano a gracidare le rane; di questa stagione i ragazzi stanno la sera appostati intorno ai laghetti, ad acchiapparle. Le rane strette in mano dànno un contatto viscido, sgusciante, ricordano le donne, così lisce e nude.

Passa un ragazzo con gli occhiali e le calze lunghe: Battistino.

– Battistino, lo sai che cos’è un gap?

Battistino batte gli occhi, curioso: – No, dimmi: cos’è?

Pin comincia a sghignazzare: – Vallo un po’ a chiedere a tua madre cos’è il gap! Digli: mamma, me lo regali un gap? Diglielo un po’: vedrai che te lo spiega!

Battistino va via tutto mortificato.

Pin sale per il carrugio, già quasi buio; e si sente solo e sperduto in quella storia di sangue e corpi nudi che è la vita degli uomini.





## II {-}

In camera di sua sorella, a guardarci in quel modo, sembra sempre che ci sia la nebbia: una striscia verticale piena di cose con intorno l’offuscarsi dell’ombra, e tutto sembra cambi dimensioni se s’avvicina o s’allontana l’occhio dalla fessura. Sembra di guardare attraverso una calza da donna e anche l’odore è lo stesso: l’odore di sua sorella che comincia al di là della porta di legno ed emana forse da quelle vesti gualcite e da quel letto mai rifatto, rincalzato senza fargli prender aria.

La sorella di Pin è sempre stata sciatta nelle faccende di casa, fin da bambina: Pin faceva dei grandi pianti in braccio a lei, da piccolo, con la testa piena di croste, e allora lei lo lasciava sul muretto del lavatoio e andava a saltare con i monelli nei rettangoli tracciati col gesso sui marciapiedi. Ogni tanto tornava la nave del loro padre, di cui Pin ricorda solo le braccia, grandi, e nude, che lo sollevavano in aria, forti braccia segnate da vene nere. Ma da quando la loro madre è morta, le sue venute sono state sempre più rade, finché nessuno l’ha più visto; si diceva che avesse un’altra famiglia in una città di là dal mare.

Ora, per abitarci, Pin più che una camera ha un ripostiglio, una cuccia al di là d’un tramezzo di legno, con una finestra che sembra una feritoia, stretta e alta com’è, e profonda nello sbieco del muro della vecchia casa. Di là c’è la camera di sua sorella filtrata dalle fessure del tramezzo, fessure da farsi venire gli occhi strabici a girarli per vedere tutt’intorno. La spiegazione di tutte le cose del mondo è lì dietro quel tramezzo; Pin ci ha passato ore e ore fin da bambino e ci ha fatto gli occhi come punte da spilli; tutto quel che succede là dentro lui lo sa, pure ancora la spiegazione del perché gli sfugge e Pin finisce per aggomitolarsi ogni notte nella sua cuccetta abbracciandosi il petto. Allora le ombre del ripostiglio si trasformano in sogni strani, di corpi che s’inseguono, si picchiano e s’abbracciano nudi, finché viene un qualcosa di grande e caldo e sconosciuto, che sovrasta su di lui, Pin, e lo carezza e lo tiene nel caldo di sé, e questo è la spiegazione di tutto, un richiamo lontanissimo di felicità dimenticata.

Ora il tedesco gira per la camera in maglietta, con le braccia rosee e cicciose come cosce, e ogni tanto viene a fuoco della fessura; a un certo punto si vedono anche le ginocchia della sorella che girano per aria ed entrano sotto le lenzuola. Pin ora deve contorcersi per seguire dove viene posato il cinturone con la pistola; è lì appeso a una spalliera di seggiola come uno strano frutto e Pin vorrebbe avere un braccio sottile come lo sguardo da far passare nella fessura, per prendere l’arma e tirarla verso di sé. Ora, il tedesco è nudo, in maglietta, e ride: ride sempre quando è nudo perché ha un fondo d’animo pudico, da ragazza. Salta nel letto e spegne la luce; Pin sa che passerà un po’ di tempo così nel buio e in silenzio, prima che il letto cominci a gemere.

Ora è il momento: Pin dovrebbe entrare nella camera scalzo e carponi e tirare giù, senza far rumore, il cinturone dalla sedia: tutto questo non per fare uno scherzo e poi ridere e canzonare, ma per qualcosa di serio e misterioso, detto dagli uomini dell’osteria, con un riflesso opaco nel bianco degli occhi. Pure, a Pin piacerebbe essere sempre amico con i grandi, e che i grandi scherzassero sempre con lui e gli dessero confidenza. Pin ama i grandi, ama fare dispetti ai grandi, ai grandi forti e sciocchi di cui conosce tutti i segreti, ama anche il tedesco, e ora questo sarà un fatto irreparabile; forse non potrà più scherzare col tedesco, dopo questo; e anche con i compagni dell’osteria sarà diverso, ci sarà qualcosa che lo lega a loro su cui non si può ridere e dire cose oscene, e loro lo guarderanno sempre con quella riga diritta tra le sopracciglia e gli chiederanno a bassa voce cose sempre più strane. Pin vorrebbe sdraiarsi nella sua cuccetta e stare a occhi aperti e fantasticare, mentre il tedesco di là sbuffa e la sorella fa dei versi come per un solletico sotto le ascelle, fantasticare di bande di ragazzi che lo accettino come loro capo, perché lui sa tante cose più di loro, e tutti insieme andare contro i grandi e picchiarli e fare cose meravigliose, cose per cui anche i grandi siano costretti a ammirarlo ed a volerlo come capo, e insieme a volergli bene e a carezzarlo sulla testa. Ma invece lui deve muoversi nella notte solo e attraverso l’odio dei grandi, e rubare la pistola al tedesco, cosa che non fanno gli altri ragazzi che giocano con pistole di latta e spade di legno. Chissà cosa direbbero se domani Pin andasse in mezzo a loro, e scoprendola a poco a poco mostrasse loro una pistola vera, lucida e minacciosa e che sembra stia per sparare da sola. Forse loro avrebbero paura e anche Pin forse avrebbe paura a tenerla nascosta sotto il giubbetto: gli basterebbe una di quelle pistole per bambini che fanno lo sparo con una striscia di fulminanti rossi e con quella fare tanto spavento ai grandi da farli cadere svenuti e chiedergli pietà.

Invece ora Pin è carponi sulla soglia della stanza, scalzo, con la testa già al di là della tenda in quell’odore di maschio e femmina che dà subito alle narici. Vede le ombre dei mobili nella stanza, il letto, la sedia, il bidé bislungo con le gambe a trespolo. Ecco: dal letto ora comincia a sentirsi quel dialogo di gemiti, ora si può avanzare carponi badando di far piano. Però forse Pin sarebbe contento che il pavimento scricchiolasse, il tedesco sentisse e tutt’a un tratto accendesse la luce, e lui fosse obbligato a scappare scalzo con sua sorella dietro che gli grida: Porco! E che tutto il vicinato sentisse e se ne parlasse anche all’osteria, e lui potesse raccontare la storia all’Autista e al Francese, con tanti particolari da essere creduto in buona fede e da far dire loro: – Basta. È andata male. Non ne parliamo più.

Il pavimento scricchiola difatti, ma molte cose scricchiolano in quel momento e il tedesco non sente: Pin già è arrivato a toccare il cinturone, e il cinturone al contatto è una cosa concreta, non magica, e scivola giù dalla spalliera della sedia in modo spaventosamente facile, senza nemmeno battere contro terra. Adesso «la cosa» è successa: la paura finta di prima diventa paura vera. Bisogna aggomitolare in fretta il cinturone intorno alla fondina, e nascondere tutto sotto il maglione senza impastoiarsi braccia e gambe: poi tornare a quattro piedi sui propri passi, pian piano e senza mai togliere la lingua di tra i denti: forse se si togliesse la lingua di tra i denti succederebbe qualcosa di spaventoso.

Una volta fuori non c’è da pensare a tornare nella sua cuccetta, a nascondere la pistola sotto il materasso come le mele rubate al mercato della frutta. Tra poco il tedesco s’alzerà e cercherà la pistola e metterà tutto a soqquadro.

Pin esce nel carrugio: non è che la pistola gli bruci addosso; così nascosta nei suoi vestiti è un oggetto come un altro e ci si può dimenticare d’averla; spiace anzi questa propria indifferenza, e a ricordarsene Pin vorrebbe gli prendesse un brivido. Una pistola vera. Una pistola vera. Pin cerca di eccitarsi col pensiero. Uno che ha una pistola vera può tutto, è come un uomo grande. Può far fare tutto quello che vuole alle donne e agli uomini minacciando d’ucciderli.

Pin ora impugnerà la pistola e camminerà sempre con la pistola puntata: nessuno potrà togliergliela e tutti ne avranno paura. Invece ha sempre la pistola avvolta nel gomitolo del cinturone, sotto il maglione e non si decide a toccarla, spera quasi che quando la cercherà non ci sia più, si sia smarrita nel calore del suo corpo.

Il posto per guardare la pistola è un sottoscala nascosto dove ci si caccia per giocare a rimpiattino, e arriva un riverbero di luce da un lampione guercio. Pin svolge il cinturone, apre la fondina e con un gesto che sembra tiri un gatto per la collottola estrae la pistola: è davvero grossa e minacciosa, se Pin avesse il coraggio di giocarci farebbe finta che fosse un cannone. Ma Pin la maneggia come fosse una bomba; la sicura, dove avrà la sicura?

Alla fine si decide a impugnarla, ma bada a non mettere le dita sotto il grilletto, tenendo ben forte l’impugnatura; pure così si può impugnare bene e puntarla contro quello che si vuole. Pin la punta prima contro il tubo della grondaia, a bruciapelo sulla lamiera, poi contro un dito, un suo dito, e fa la faccia feroce tirando indietro la testa e dicendo tra i denti: «la borsa o la vita», poi trova una scarpa vecchia e la punta contro la scarpa vecchia, contro il calcagno, poi nell’interno, poi passa la bocca dell’arma sulle cuciture della tomaia. È una cosa molto divertente: una scarpa, un oggetto così conosciuto, specie per lui, garzone ciabattino, e una pistola, un oggetto così misterioso, quasi irreale; a farli incontrare uno con l’altro si possono fare cose mai pensate, si possono far loro recitare storie meravigliose.

Ma a un certo punto Pin non resiste più alla tentazione e si punta la pistola contro la tempia: è una cosa che dà le vertigini. Avanti, fino a toccare la pelle e sentire il freddo del ferro. Si potrebbe posare il dito sul grilletto, adesso: no, meglio premere la bocca della canna contro lo zigomo fino a farsi male, e sentire il cerchio di ferro con dentro il vuoto dove nascono gli spari. A staccare l’arma dalla tempia, di botto, forse il risucchio dell’aria farà esplodere un colpo: no, non esplode. Ora si può mettere la canna in bocca e sentire il sapore sotto la lingua. Poi, cosa più paurosa di tutte, portarla agli occhi e guardarci dentro, nella canna buia che sembra fonda come un pozzo. Una volta Pin ha visto un ragazzo che s’era sparato in un occhio con un fucile da caccia, mentre lo portavano all’ospedale: aveva un gran grumo di sangue su mezza faccia, e l’altra mezza tutta puntini neri della polvere.

Ora Pin ha giocato con la pistola vera, ha giocato abbastanza: può darla a quegli uomini che gliel’hanno chiesta, non vede l’ora di darla. Quando non l’avrà più sarà come se non l’avesse rubata e il tedesco avrà un bell’andare in bestia con lui, lui lo potrà di nuovo prendere in giro.

Il primo impulso sarebbe di entrare nell’osteria di corsa, annunciando agli uomini: «Ce l’ho e non mi scappa!» tra l’entusiasmo di tutti che esclamano: «Ma no!» Poi gli sembra che sia più spiritoso chiedere loro: «Indovina cos’ho portato?» e farli spazientire un po’ prima di dirlo. Ma certo loro penseranno subito alla pistola, tanto vale entrare subito in argomento, e cominciare a raccontar loro la storia in dieci maniere differenti, facendo capire che è andata male, e quando loro son più sulle spine e non si raccapezzano più, posare la pistola sul tavolo e dire: «Guarda cosa mi son trovato in tasca», e vedere un po’ che faccia fanno.

Pin entra nell’osteria in punta di piedi, zitto; gli uomini parlottano sempre intorno a un tavolo, coi gomiti che sembra ci abbiano messo radici. Solo quell’uomo sconosciuto non c’è più e la sua sedia è vuota. Pin è dietro a loro e non se ne sono accorti: lui s’aspetta che tutt’a un tratto lo vedano e sussultino, facendogli piovere addosso una doccia di sguardi interrogativi. Ma nessuno si volta. Pin muove una sedia. Giraffa torce il collo, lo smiccia; poi torna a parlare piano.

– Begli uomini, – fa Pin.

Gli dànno un’occhiata.

– Brutto muso, – gli fa Giraffa, amichevole.

Nessuno dice più niente.

– Allora, – fa Pin.

– Allora, – dice Gian l’Autista, – cosa ci racconti di nuovo?

Pin è un po’ smontato.

– Ben, – fa il Francese, – sei giù di morale? Cantacene un po’ una, Pin.

«Qui, – pensa Pin, – fanno l’indiano anche loro, ma non stan più nella pelle dalla curiosità.»

– Alé, – dice. Ma non attacca: ha la gola appiccicata, secca, come quando si ha paura di piangere.

– Alé, – ripete. – Quale vi canto?

– Quale? – fa Miscèl.

E Giraffa: – Che barba, stasera, vorrei già essere a dormire.

Pin non ne può più del gioco: – E quell’uomo? – chiede.

– Chi?

– Quell’uomo seduto lì, prima?

– Ah, – dicono gli altri e scuotono il capo. Poi riprendono a parlottare tra loro.

– Io, – dice il Francese agli altri, – con questi del comitato non mi comprometterei troppo. Non me la sento d’andar di mezzo per la faccia loro.

– Ben, – dice Gian l’Autista. – Noi cosa s’è fatto? S’è detto: vedremo. Intanto è bene averci un collegamento con loro senza impegnarci, e prendere tempo. Io coi tedeschi poi ci ho un conto da regolare da quando s’era al fronte insieme, e se c’è da battermi, mi batto volentieri.

– Ben, – dice Miscèl. – Guarda che coi tedeschi non si scherza e non si sa come andrà a finire. Il comitato vuole che facciamo il gap; bene, noi facciamo il gap per conto nostro.

– Intanto, – fa Giraffa, – gli facciamo vedere che siamo dalla loro, e ci armiamo. Una volta che siamo armati...

Pin è armato: sente la pistola sotto la giacchetta e ci mette una mano sopra, come se gliela volessero portar via.

– Ne avete armi, voi? – chiede.

– Non ci stare a pensare, – fa il Giraffa. – Tu pensa a quella pistola del tedesco, siamo intesi.

Pin rizza gli orecchi; ora dirà: indovinate, dirà.

– Guarda un po’ di non perderla d’occhio, se ti capita sottomano...

Non è come Pin avrebbe voluto, perché importa loro tanto poco, adesso? Vorrebbe non aver ancora preso la pistola, vorrebbe tornar dal tedesco e rimetterla al suo posto.

– Per una pistola, – dice Miscèl, – non val la pena rischiare. Poi è un modello antiquato: pesante, s’inceppa.

– Intanto, – dice Giraffa, – bisogna far vedere al comitato che facciamo qualcosa, questo è importante –. E continuano a parlottare sottovoce.

Pin non sente più niente: ormai è sicuro che non darà loro la pistola; ha i lucciconi agli occhi e una rabbia gli stringe le gengive. I grandi sono una razza ambigua e traditrice, non hanno quella serietà terribile nei giochi propria dei ragazzi, pure hanno anch’essi i loro giochi, sempre più seri, un gioco dentro l’altro che non si riesce mai a capire qual è il gioco vero. Prima sembrava che giocassero con l’uomo sconosciuto contro il tedesco, adesso da soli contro l’uomo sconosciuto, non ci si può mai fidare di quel che dicono.

– Ben, cantacene un po’ una, Pin, – dicono adesso, come se nulla fosse successo, come se non ci fosse stato un patto severissimo tra lui e loro, un patto consacrato da una parola misteriosa: gap.

– Alé, – fa Pin, con le labbra che gli tremano, pallido. Sa che non può cantare. Vorrebbe piangere, invece scoppia in uno strillo in i che schioda i timpani e finisce in uno scatenio d’improperi: – Bastardi, figli di quella cagna impestata di vostra madre vacca sporca lurida puttana!

Gli altri stanno a guardare cosa gli è preso, ma Pin è già scappato dall’osteria.

Fuori, il primo impulso sarebbe di cercare quell’uomo, quello che chiamano «comitato» e dargli la pistola: ora è l’unica persona che Pin sente di rispettare, anche se prima, così zitto e serio, gli ispirava diffidenza. Ma adesso è l’unico che potrebbe comprenderlo, ammirarlo per il suo gesto, e forse lo prenderebbe con sé a far la guerra contro i tedeschi, loro due soli, armati di pistola, appostati agli angoli delle vie. Ma Comitato chissà dov’è adesso: non si può chiedere in giro, nessuno l’aveva mai visto prima.

La pistola rimane a Pin e Pin non la darà a nessuno e non dirà a nessuno che l’ha. Solo farà capire che è dotato d’una forza terribile e tutti lo obbediranno. Chi ha una pistola vera dovrebbe fare dei giochi meravigliosi, dei giochi che nessun ragazzo ha fatto mai, ma Pin è un ragazzo che non sa giocare, che non sa prender parte ai giochi né dei grandi né dei ragazzi. Pure adesso Pin andrà lontano da tutti e giocherà tutto solo con la sua pistola, farà giochi che nessun altro conosce e nessun altro potrà mai sapere.

È notte: Pin ha scantonato fuori dal mucchio delle vecchie case, per le stradine che vanno tra orti e scoscendimenti ingombri d’immondizie. Nel buio le reti metalliche che cintano i semenzai gettano una maglia d’ombre sulla terra grigio-lunare; le galline ora dormono in fila sui pali dei pollai e le rane sono tutte fuor d’acqua e fanno cori per tutto il torrente, dalla sorgente alla foce. Chissà cosa succederebbe a sparare a una rana: forse resterebbe solo una bava verde schizzata su qualche pietra.

Pin va per i sentieri che girano intorno al torrente, posti scoscesi dove nessuno coltiva. Ci sono strade che lui solo conosce e che gli altri ragazzi si struggerebbero di sapere: un posto, c’è, dove fanno il nido i ragni, e solo Pin lo sa ed è l’unico in tutta la vallata, forse in tutta la regione: mai nessun ragazzo ha saputo di ragni che facciano il nido, tranne Pin.

Forse un giorno Pin troverà un amico, un vero amico, che capisca e che si possa capire, e allora a quello, solo a quello, mostrerà il posto delle tane dei ragni. È una scorciatoia sassosa che scende al torrente tra due pareti di terra ed erba. Lì, tra l’erba, i ragni fanno delle tane, dei tunnel tappezzati d’un cemento d’erba secca; ma la cosa meravigliosa è che le tane hanno una porticina, pure di quella poltiglia secca d’erba, una porticina tonda che si può aprire e chiudere.

Quando ha fatto qualche grosso dispetto e a furia di ridere il petto gli si è riempito d’una tristezza opaca, Pin vaga tutto solo per i sentieri del fossato e cerca il posto dove fanno la tana i ragni. Con uno stecco lungo si può arrivare fino in fondo ad una tana, e infilzare il ragno, un piccolo ragno nero, con dei disegnini grigi come sui vestiti d’estate delle vecchie bigotte.

Pin si diverte a disfare le porte delle tane e a infilzare i ragni sugli stecchi, anche a prendere i grilli e a guardarli da vicino sulla loro assurda faccia di cavallo verde, e poi tagliarli a pezzi e fare strani mosaici con le zampe su una pietra liscia.

Pin è cattivo con le bestie: sono esseri mostruosi e incomprensibili come gli uomini; dev’essere brutto essere una piccola bestia, cioè essere verde e fare la cacca a gocce, e aver sempre paura che venga un essere umano come lui, con una enorme faccia piena d’efelidi rosse e nere e con dita capaci di fare a pezzi i grilli.

Ora Pin è solo tra le tane dei ragni e la notte è infinita intorno a lui come il coro delle rane. È solo ma ha la pistola con sé, e ora si mette il cinturone con la fondina sul sedere come il tedesco; solo che il tedesco è grasso e a Pin il cinturone può stare a tracolla, come le bandoliere di quei guerrieri che si vedono nei cinema. Adesso si può estrarre la pistola con un grande gesto come si snudasse una spada, e dire anche: «All’assalto, miei prodi!» come fanno i ragazzi quando giocano ai pirati. Ma non si sa che gusto ci provino quei mocciosi a dire e a fare quelle cose: Pin dopo aver fatto qualche salto per il prato, con la pistola puntata, mirando alle ombre dei ceppi d’olivo, s’è già annoiato e non sa più cosa fare dell’arma.

I ragni sotterranei in quel momento rodono vermi o si accoppiano i maschi con le femmine emettendo fili di bava: sono esseri schifosi come gli uomini, e Pin infila la canna della pistola nell’imboccatura della tana con una voglia di ucciderli. Chissà cosa succederebbe se partisse un colpo, le case sono distanti e nessuno capirebbe da dove viene. Poi spesso i tedeschi e quelli della milizia sparano la notte addosso a chi gira nel coprifuoco.

Pin ha il dito sul grilletto, con la pistola puntata nella tana di un ragno: resistere alla voglia di schiacciare il grilletto è difficile, ma certo la pistola è in sicurezza e Pin non sa come si toglie.

A un tratto lo sparo parte così d’improvviso che Pin non se n’è nemmeno accorto d’aver schiacciato: la pistola fa un balzo indietro nella sua mano, fumante e tutta sporca di terra. Il tunnel della tana è crollato, sopra ci scende una piccola frana di terriccio e l’erba intorno è strinata.

Pin è preso da spavento prima, e poi da gioia: tutto è stato così bello e l’odore della polvere è così buono. Ma la cosa che lo spaventa davvero è che le rane tacciono d’improvviso, e non si sente più niente come se quello sparo avesse ucciso tutta la terra. Poi una rana, molto distante, ricomincia a cantare, e poi un’altra più vicina, e altre più vicine ancora, finché il coro riprende e a Pin sembra gridino più forte, molto più forte di prima. E dalle case un cane abbaia e una donna si mette a chiamare dalla finestra. Pin non sparerà più perché quei silenzi e quei rumori gli fanno paura. Però un’altra notte tornerà e non ci sarà nulla che potrà spaventarlo e allora sparerà tutti i colpi della pistola anche contro i pipistrelli e i gatti che girano a quell’ora intorno ai pollai.

Ora bisogna trovare un posto dove nascondere la pistola: il cavo d’un albero d’ulivo; o meglio: sotterrarla, o meglio ancora scavare una nicchia nella parete erbosa dove sono i nidi di ragno e coprire tutto con terriccio ed erba. Pin scava con le unghie in un punto dove il terriccio è già tutto corroso dalle fitte gallerie dei ragni, ci mette dentro la pistola nella fondina sfilata dal cinturone, e copre tutto con terriccio ed erba, e pezzi di parete di tana, biascicati dalle bocche dei ragni. Poi mette delle pietre in modo che lui solo possa riconoscere il posto, e va via frustando i cespugli con la cinghia del cinturone. La via del ritorno è per i beudi, i piccoli canali sopra il fossato con una stretta linea di pietre per camminarci.

Pin andando trascina la coda del cinturone nell’acqua della cunetta e fischia per non sentire quel gracidio di rane che sembra s’amplifichi di momento in momento.

Poi ci sono gli orti e le immondizie e le case: e arrivando lì Pin sente delle voci non italiane che parlano. C’è il coprifuoco ma lui spesso gira lo stesso di notte perché è un bambino e le pattuglie non gli dicono niente. Ma Pin questa volta ha paura perché forse quei tedeschi sono lì a cercare chi ha sparato. Vengono verso di lui e Pin vorrebbe scappare, ma quelli già gli gridano qualcosa e lo raggiungono. Pin s’è rattrappito in un gesto di difesa con la cinghia del cinturone come una frusta. Ma ecco che i tedeschi guardano proprio la cinghia del cinturone, vogliono quella; e tutt’a un tratto lo prendono per la collottola e lo portano via. Pin dice moltissime cose: preghiere, lamenti, insulti, ma i tedeschi non capiscono nulla; sono peggio, molto peggio delle guardie municipali.

Nel vicolo ci sono addirittura delle pattuglie tedesche e fasciste armate, e della gente presa ed arrestata, anche Miscèl il Francese. Pin viene fatto passare in mezzo salendo per il vicolo. C’è buio; solo in cima ai gradini c’è un punto illuminato da un lampione guercio per l’oscuramento.

Alla luce del lampione guercio, in cima al carrugio, Pin vede il marinaio con la grassa faccia imbestialita che punta un dito contro di lui.





## III {-}

I tedeschi sono peggio delle guardie municipali. Con le guardie, se non altro, ci si poteva mettere a scherzare, dire: – Se mi lasciate libero vi faccio andare a letto gratis con mia sorella.

Invece i tedeschi non capiscono quello che si dice, i fascisti sono gente sconosciuta, gente che non sa nemmeno chi è la sorella di Pin. Sono due razze speciali: quanto i tedeschi sono rossicci, carnosi, imberbi, tanto i fascisti sono neri, ossuti, con le facce bluastre e i baffi da topo.

Nel comando tedesco, al mattino, il primo a essere interrogato è Pin. Di fronte a lui sono un ufficiale tedesco con la faccia da bimbo e un interprete fascista con la barbetta. Poi, in un angolo, il marinaio e, seduta, la sorella di Pin. Tutti hanno l’aria seccata: a quanto pare il marinaio, per una pistola rubata, deve aver montato tutta una storia, forse perché non l’incolpino d’essersela lasciata prendere, e deve aver raccontato molte cose false.

Sul tavolo dell’ufficiale c’è il cinturone, e la prima domanda rivolta a Pin è: come mai avevi in mano questo? Pin è mezzo addormentato: hanno passato la notte sdraiati sul pavimento d’un corridoio e Miscèl il Francese s’è messo vicino a lui e ogni volta che Pin stava per prender sonno Miscèl gli dava una gomitata forte da fargli male, e gli diceva in un soffio: – Se parli ti facciamo la pelle.

E Pin: – Crepa.

– Neanche se ti battono, hai capito? devi dire una parola di noialtri.

E Pin: – Morissi.

– È inteso che se i soci non mi vedono tornare a casa fanno la pelle a te.

E Pin: – Ti venisse un cancro all’anima.

Miscèl è uno che prima della guerra lavorava in Francia negli alberghi e se la passava bene, anche se ogni tanto gli dicevano macaronì o cochon fassiste; poi nel ’40 hanno cominciato a metterlo in campo di concentramento e d’allora in poi tutto è andato di traverso: disoccupazione, rimpatrio, malavita.

Le sentinelle a un certo punto si sono accorte di quel parlottare tra Pin e il Francese e hanno portato via il ragazzo perché era il principale indiziato e non doveva comunicare con nessuno. A Pin non è riuscito di dormire; a essere picchiato c’era abituato e non gli faceva tanta paura, ma quello che lo tormentava era un dubbio sull’atteggiamento da prendere nell’interrogatorio: da una parte avrebbe voluto vendicarsi di Miscèl e di tutti gli altri e dire subito ai comandanti tedeschi che la pistola l’aveva data a quelli dell’osteria e che c’era anche il gap; ma fare la spia era un altro atto irreparabile come rubare la pistola, voleva dire non più farsi pagare da bere all’osteria, cantare e stare a sentire cose sconce. E poi forse ci sarebbe andato di mezzo Comitato, sempre così triste e scontento, e questo a Pin sarebbe rincresciuto perché Comitato era l’unica persona buona in mezzo a tutti loro. Pin ora vorrebbe che Comitato arrivasse, chiuso nel suo impermeabile, entrasse nell’ufficio degli interrogatori e dicesse: «Gli ho detto io di prendere la pistola». Questo sarebbe un bel gesto, degno di lui e nemmeno gli succederebbe niente, perché proprio nel momento in cui gli esse-esse farebbero per imprigionarlo si sentirebbe come al cinematografo: «Arrivano i nostri!» ed entrerebbero di corsa gli uomini di Comitato a liberare tutti.

– L’ho trovato, – risponde Pin all’ufficiale tedesco che gli ha chiesto del cinturone. Allora l’ufficiale solleva il cinturone e gli dà una frustata a una guancia con tutte le sue forze. Pin a momenti va per terra, sente come un volo d’aghi che gli si conficcano nelle lentiggini, e il sangue scorrergli per la guancia già gonfia.

La sorella dà un grido. Pin non può fare a meno di pensare a quante volte lei l’ha picchiato, forte quasi come adesso, e che è una bugiarda a far tanto la sensibile. Il fascista conduce via la sorella, il marinaio attacca un discorso tedesco complicato indicando Pin, ma l’ufficiale lo fa star zitto. Chiedono a Pin se non si è deciso a dir la verità: chi l’ha mandato a rubar la pistola?

– La pistola l’ho presa per sparare a un gatto e poi restituirla, – dice Pin ma non gli riesce di fare la faccia ingenua, si sente tutto gonfio e ha una voglia lontana di carezze.

Una nuova frustata sull’altra guancia, meno forte però. Ma Pin, che si ricorda del suo sistema con le guardie municipali, dà un grido straziante prima ancora che la cinghia l’abbia toccato, e non la smette più. Comincia una scena in cui Pin salta urlando e piangendo per la stanza e i tedeschi lo rincorrono per acchiapparlo o per dargli frustate, e lui grida, frigna, insulta e risponde alle domande che continuano a fargli con risposte sempre più inverosimili.

– Dove hai messo la pistola?

Ora Pin può anche dire la verità: – Alle tane dei ragni.

– Dove sono?

Pin in fondo preferirebbe essere amico con questi uomini; anche le guardie municipali gliele suonano sempre e poi si mettono a scherzare su sua sorella. Se ci si mettesse d’accordo sarebbe bello spiegare a costoro dove fanno il nido i ragni e che loro s’interessassero e venissero con lui, che mostrerebbe loro tutti i posti. Poi andrebbero insieme all’osteria a comprare del vino e poi tutti in camera di sua sorella a bere, fumare e vederla ballare. Ma i tedeschi e i fascisti sono razze imberbi o bluastre con cui non ci si può intendere, e continuano a picchiarlo e Pin non dirà mai loro dove sono i nidi di ragno, non l’ha mai detto agli amici, figuriamoci se lo dice a loro.

Piange, invece, un pianto enorme, esagerato, totale come il pianto dei neonati, misto a urli e imprecazioni e a pestate di piedi che lo si sente per tutto il casamento del comando tedesco. Non tradirà Miscèl, Giraffa, l’Autista e gli altri: sono i suoi veri compagni. Pin ora è pieno d’ammirazione per loro perché sono nemici di quelle razze bastarde. Miscèl può star sicuro che Pin non lo tradirà, di là certo sentirà i suoi gridi e dirà: «Un ragazzo di ferro, Pin, resiste e non parla».

Difatti il baccano piantato da Pin si sente dappertutto, gli ufficiali degli altri uffici cominciano a essere seccati, al comando tedesco c’è sempre un viavai di gente per permessi e forniture, non è bene che tutti sentano che loro battono anche i bambini.

L’ufficiale con la faccia infantile riceve l’ordine di smettere l’interrogatorio; continuerà un altro giorno e in altra sede. Ma far stare zitto Pin adesso è un problema. Loro vogliono spiegargli che tutto è finito ma Pin copre la loro voce coi suoi strilli. Gli si avvicinano in molti, per calmarlo, ma lui scappa e si divincola e raddoppia i piagnistei. Fanno entrare sua sorella che lo consoli e lui a momenti le salta addosso per morderla. Dopo un po’ c’è un gruppetto di militi e di tedeschi attorno a lui che cercano di rabbonirlo, qualcuno gli fa una carezza, qualcuno cerca d’asciugargli le lacrime.

Alla fine, stremato, Pin si cheta, ansimando senza più voce in gola. Ora un milite lo condurrà alla prigione e domani lo riaccompagnerà all’interrogatorio.

Pin esce dall’ufficio col milite armato che lo segue; ha la faccia piccola piccola sotto l’ispido dei capelli, gli occhi strizzati e le lentiggini lavate dal pianto.

Sulla porta incontrano Miscèl il Francese che esce, libero.

– Ciao, Pin, – dice, – vado a casa. Prendo servizio domani.

Pin lo smiccia con gli occhietti rossi, a bocca aperta.

– Sì. Ho fatto domanda per la brigata nera. Mi hanno spiegato i vantaggi, lo stipendio che si piglia. Poi, sai, nei rastrellamenti puoi girare per le case a perquisire dove vuoi. Domani mi vestono e mi armano. In gamba, Pin.

Il milite che accompagna Pin alla prigione ha il berrettino nero col fascio rosso ricamato sopra: è un ragazzotto basso basso, con un moschetto più alto di lui. Non appartiene alla razza bluastra dei fascisti.

Già da cinque minuti camminano e ancora nessuno dei due ha detto niente.

– Se vuoi ti ci fanno entrare anche te nella brigata nera –, dice il milite a Pin.

– Se voglio entro nella... di quella vacca della tua bisnonna, – gli risponde Pin senza scomporsi. Il milite vuol far l’offeso:

– Di’, oh, con chi ti credi? Di’, oh, chi t’ha insegnato? – e si ferma.

– Dài, portami in galera, sbrigati, – lo tira Pin.

– E cosa ti credi, che in galera vai a star tranquillo? Tutti i momenti ti fanno andare all’interrogatorio e ti gonfiano dalle botte. Ti piace pigliar le botte?

– A te invece piace essere in... – fa Pin.

– A te, – fa il milite.

– A te, a tuo padre e a tuo nonno, – fa Pin.

Il milite è un po’ tonto e ci rimane male tutte le volte.

– Se non vuoi che ti picchino, entra nella brigata nera.

– E poi? – fa Pin.

– E poi fai i rastrellamenti.

– Tu li fai i rastrellamenti?

– No. Io sono piantone al comando.

– Ma va’. Chissà quanti ribelli hai ammazzato e non lo vuoi raccontare.

– Ti giuro. Mai stato in un rastrellamento.

– Mai tranne quelle volte che c’eri.

– Tranne quella volta in cui m’han preso.

– Han preso anche te in un rastrellamento?

– Sì, è stato proprio un bel rastrellamento, proprio ben fatto. Pulizia completa. Anche me hanno preso. Ero nascosto in un pollaio. Proprio un bel rastrellamento.

Con Miscèl Pin è rimasto male non perché giudichi che ha compiuto una brutta azione, che sia un traditore. Solo lo irrita lo sbagliarsi tutte le volte e non poter mai prevedere quel che fanno i grandi. Lui s’aspetta che uno pensi in un modo, e invece quello pensa in un altro, con cambiamenti che non si possono mai prevedere.

In fondo anche a Pin piacerebbe essere nella brigata nera, girare tutto bardato di teschi e di caricatori da mitra, far paura alla gente e stare in mezzo agli anziani come uno dei loro, legato a loro da quella barriera d’odio che li separa dagli altri uomini. Forse, ripensandoci, deciderà d’entrare nella brigata nera, almeno potrà recuperare la pistola e forse potrà tenerla e portarla apertamente sulla divisa; e potrà anche vendicarsi dell’ufficiale tedesco e del graduato fascista con dei dispetti, per rifarsi in risate di tutti i pianti e gli urli.

C’è una canzone delle brigate nere che dice: E noi di Mussolini ci chiaman farabutti... e poi ci sono delle parole oscene: le brigate nere possono cantare canzoni oscene per le vie perché sono farabutti di Mussolini, questo è meraviglioso. Però il piantone è uno stupido e gli dà ai nervi, perciò lui risponde male a ogni cosa che dice.

La prigione è una grande villa d’inglesi requisita, perché nella vecchia fortezza sul porto i tedeschi hanno piazzato la contraerea. È una villa strana, in mezzo a un parco d’araucarie, che già prima forse aveva l’aria di una prigione, con molte torri e terrazze e camini che girano al vento, e inferriate che già c’erano da prima, oltre a quelle aggiunte.

Adesso le stanze sono adattate a celle, strane celle con il pavimento di legno e linoleum, con grandi camini di marmo murati, con lavabi e bidè turati da stracci. Sulle torrette stanno sentinelle armate e sulle terrazze i detenuti fanno la coda per il rancio e si sparpagliano un po’ per il passeggio.

Quando Pin arriva è l’ora del rancio e tutt’a un tratto si ricorda d’aver molta fame. Dànno una scodella anche a lui e lo mettono in coda.

Tra i detenuti sono molti renitenti alla chiamata alle armi e anche molti per reati annonari, macellatori clandestini, trafficanti in benzina e in sterline. I delinquenti comuni sono rimasti in pochi, ormai che nessuno dà più la caccia ai ladri; gente che aveva da scontare vecchie condanne, e non è più in età di chiedere l’arruolamento per avere il condono. I politici si distinguono per i lividi che hanno sulla faccia, per il modo come si muovono con le ossa rotte dagli interrogatori.

Anche Pin è un «politico», lo si vede subito. Sta mangiando la sua brodaglia, quando gli s’avvicina un ragazzo grande e grosso, con la faccia più gonfia e livida della sua e i capelli rasi sotto un berretto a visiera.

– T’hanno conciato bene, compagno, – dice.

Pin lo guarda, non sa ancora come deve trattarlo: – E te no? – dice.

Il testarapata fa: – A me ogni giorno mi portano all’interrogatorio e mi picchiano con un nervo di bue.

Lo dice con grande importanza come facessero un onore speciale per lui.

– Se vuoi la mia minestra tieni, – dice a Pin. – Io non posso mangiare perché ho la gola piena di sangue.

E sputa in terra una schiumetta rossa. Pin lo guarda con interesse: ha sempre avuto una strana ammirazione per chi riesce a sputare il sangue; gli piaceva molto vedere come fanno i tisici.

– Allora sei tisico, – dice al testarapata.

– Forse m’han fatto diventare tisico, – consente il testarapata con importanza. Pin ha dell’ammirazione per lui; forse diventeranno veri amici. E poi gli ha dato la sua minestra e Pin la gradisce molto perché ha fame.

– Se continua così, – dice il testarapata, – mi rovinano per tutta la vita.

Pin dice: – E tu perché non t’iscrivi nella brigata nera?

Allora il testarapata s’alza e gli pianta in faccia gli occhi tumefatti: – Di’, ma lo sai chi sono io?

– No, chi sei? – fa Pin.

– Hai mai sentito parlare di Lupo Rosso?

Lupo Rosso! e chi non ne ha sentito parlare? A ogni colpo incassato dai fascisti, a ogni bomba che scoppia nella villetta d’un comando, a ogni spia che sparisce e non si sa dove va a finire, la gente dice un nome sottovoce: Lupo Rosso. Pin sa anche che Lupo Rosso ha sedici anni, e prima lavorava alla «Todt» come meccanico: altri giovani che lavoravano nella «Todt» per avere l’esonero gliene hanno parlato, perché portava il berretto alla russa e parlava sempre di Lenin, tanto che l’avevano soprannominato Ghepeù. Aveva anche la mania della dinamite e delle bombe a orologeria e pareva che si fosse messo nella «Todt» per imparare come si fanno le mine. Finché un giorno il ponte della ferrovia è saltato in aria e Ghepeù non si è fatto più vedere alla «Todt»: stava sui monti e calava in città alla notte, con una stella bianca, rossa e verde sul berretto russo, e una grossa pistola. S’era fatto crescere i capelli lunghi e si chiamava Lupo Rosso.

Ora Lupo Rosso è davanti a lui, col berretto alla russa senza più la stella, la grossa testa rasa, gli occhi pesti, e sputa sangue.

– Sì: sei tu? – dice Pin.

– Io, – fa Lupo Rosso.

– E quando t’han preso?

– Giovedì sul ponte del Borgo: armato e con la stella sul berretto.

– E cosa ti fanno?

– Forse, – dice con la sua aria d’importanza, – mi fucilano.

– Quando?

– Forse domani.

– E tu?

Lupo Rosso sputa sangue per terra: – Chi sei tu? – chiede a Pin. Pin dice il suo nome. Ha sempre desiderato d’incontrare Lupo Rosso, Pin, di vederlo sbucare una notte nei vicoli della città vecchia, ma ne ha avuto sempre anche un po’ paura, per via di sua sorella che va coi tedeschi.

– Perché sei qui? – chiede Lupo Rosso. Ha quasi lo stesso tono perentorio dei fascisti che interrogano.

Adesso tocca a Pin darsi un po’ d’arie: – Ho portato via una pistola a un tedesco.

Lupo Rosso fa una smorfia favorevole, serio: – Sei in banda? – chiede. Pin dice: – Io no.

– Non sei organizzato? Non sei in un gap?

Pin è tutto contento di risentire quella parola: – Sì, sì, – dice, – gap!

– Con chi sei?

Pin ci pensa un po’ su, poi fa: – Con Comitato.

– Chi?

– Comitato, non lo conosci? – Pin vuol fare l’aria di superiorità ma non gli riesce bene. – Uno magro, con l’impermeabile chiaro.

– Tu racconti delle storie, il comitato sono in tante persone, che nessuno sa chi siano, e preparano l’insurrezione. Tu non sai proprio niente.

– Se nessuno sa chi siano non lo sai nemmeno tu.

A Pin non piace parlare con i ragazzi di quella età perché vogliono fare i superiori e non gli dànno confidenza e lo trattano come un bambino.

– Io lo so, – dice Lupo Rosso, – io sono uno del sim.

Un’altra parola misteriosa: sim! gap! Chissà quante parole così ci saranno: a Pin piacerebbe saperle tutte.

– So tutto anch’io, invece, – dice. – So che tu ti chiami anche Ghepeù.

– Non è vero, – dice Lupo Rosso, – non bisogna chiamarmi così.

– Perché?

– Perché noi non facciamo la rivoluzione sociale, ma la liberazione nazionale. Quando il popolo avrà liberato l’Italia, inchiodiamo la borghesia alle sue responsabilità.

– Come? – dice Pin.

– Così. Inchiodiamo la borghesia alle sue responsabilità. Me l’ha spiegato il commissario di brigata.

– Lo sai chi è mia sorella? – È una domanda che non c’entra, ma Pin ne ha basta di fare discorsi di cui non si capisce niente e preferisce entrare negli argomenti abituali.

– No, – fa Lupo Rosso.

– È la Nera di Carrugio Lungo.

– E chi è?

– Come chi è. Tutti la conoscono, mia sorella. La Nera di Carrugio Lungo.

È incredibile che un ragazzo come Lupo Rosso non abbia mai sentito parlare di sua sorella. Nella città vecchia anche i bambini di sei anni cominciano a parlarne e spiegano alle bambine com’è che fa quand’è a letto con gli uomini.

– Di’, non sa chi è mia sorella. Questa è buona...

Pin vorrebbe chiamare anche gli altri detenuti e cominciare a fare il buffone.

– Io le donne per ora non le guardo nemmeno, – dice Lupo Rosso. – Una volta fatta l’insurrezione, ci sarà tempo...

– Ma se ti fucilano domani? – dice Pin.

– Bisogna vedere, chi fa prima, se loro a fucilare me o io a fucilare loro.

– Come sarebbe a dire?

Lupo Rosso ci pensa un po’ su, poi si china all’orecchio di Pin: – Ci ho un piano che se mi riesce, prima di domani son scappato e allora tutti questi bastardi fascisti che mi hanno fatto del male la pagano uno per uno.

– Scappi, e dove vai?

– Al distaccamento vado. Dal Biondo. E prepariamo un’azione che se ne accorgeranno.

– Mi porti con te?

– No.

– Sii bravo, Lupo, portami con te.

– Mi chiamo Lupo Rosso, – precisa l’altro. – Quando il commissario m’ha detto che Ghepeù non andava bene, io gli ho chiesto come mi potevo chiamare, e lui ha detto: chiamati Lupo. Allora io gli ho detto che volevo un nome con qualcosa di rosso perché il lupo è un animale fascista. E lui m’ha detto: allora chiamati Lupo Rosso.

– Lupo Rosso, – dice Pin, – senti, Lupo Rosso: perché non vuoi portarmi con te?

– Perché sei un bambino, ecco perché.

Dapprincipio, per la questione della pistola rubata, sembrava che con Lupo Rosso si potesse diventare amici sul serio. Ma poi ha continuato a trattarlo come un bambino, e questo dà ai nervi. Con gli altri ragazzi di quella età, Pin può almeno far valere la sua superiorità parlando di come son fatte le donne, ma con Lupo Rosso quest’argomento non attacca. Pure sarebbe bello andare in banda con Lupo Rosso e fare grandi esplosioni per fare crollare i ponti, e scendere in città sparando raffiche contro le pattuglie. Forse più bello ancora che la brigata nera. Soltanto la brigata nera ha le teste da morto che sono molto più d’effetto delle stelle tricolori.

È una cosa che non sembra vera essere lì a parlare con uno che domani forse sarà fucilato, su quel terrazzo pieno d’uomini che mangiano abbovati in terra, tra comignoli che girano al vento e le guardie carcerarie sulle torrette con i mitra puntati. Sembra uno scenario incantato: tutt’intorno il parco con le ombre nere degli alberi d’araucaria. Pin ha quasi dimenticato le botte che ha preso, e non è ben sicuro che non sia un sogno.

Ma ora le guardie carcerarie li mettono in fila per farli tornare in cella.

– Dove sei di cella? – chiede Lupo Rosso a Pin.

– Non so dove mi metteranno, – dice Pin, – non ci sono ancora stato.

– M’interessa sapere dove sei, – dice Lupo Rosso.

– Perché? – fa Pin.

– Poi lo saprai.

A Pin fanno rabbia quelli che dicono sempre: poi lo saprai.

Tutt’a un tratto, nella fila dei detenuti che s’incamminano gli sembra di vedere una faccia conosciuta, molto conosciuta.

– Di’, Lupo Rosso, lo conosci quello là davanti, secco secco, che cammina in quella maniera?...

– È un detenuto comune. Lascialo stare. Sui detenuti comuni non c’è da fare assegnamento.

– Perché? Io lo conosco!

– Sono proletariato senza coscienza di classe, – dice Lupo Rosso.