# Ultimo viene il corvo {-}

## Un pomeriggio, Adamo {-}

Il nuovo giardiniere era un ragazzo coi capelli lunghi, e una crocetta di stoffa in testa per tenerli fermi. Adesso veniva su per il viale con l’innaffiatoio pieno, sporgendo l’altro braccio per bilanciare il carico. Innaffiava le piante di nasturzio, piano piano, come versasse caffelatte: in terra, al piede delle piantine, si dilatava una macchia scura; quando la macchia era grande e molle lui rialzava l’innaffiatoio e passava a un’altra pianta. Il giardiniere doveva essere un bel mestiere perché si potevano fare tutte le cose con calma. Maria-nunziata lo stava guardando dalla finestra della cucina. Era un ragazzo già grande, eppure portava ancora i calzoni corti. E quei capelli lunghi che sembrava una ragazza. Smise di risciacquare i piatti e batté sui vetri.

- Ragazzo, - disse.

Il ragazzo-giardiniere alzò la testa, vide Maria-nunziata e sorrise. Anche Maria-nunziata si mise a ridere, per rispondere a lui, e perché non aveva mai visto un ragazzo coi capelli così lunghi e con una crocetta come quella in testa. Allora il ragazzo-giardiniere le fece «vieni-qui» con la mano e Maria-nunziata continuava a ridere per quel suo modo buffo di fare i gesti, e si mise anche lei a fare gesti per spiegargli che aveva da rigovernare i piatti. Ma il ragazzo- giardiniere le faceva «vieni-qui» con una mano e con l’altra indicava i vasi delle dalie. Perché indicava i vasi delle dalie? Maria-nunziata schiuse i vetri e mise la testa fuori.

- Cosa c’è? - disse, e si mise a ridere.

- Di’: vuoi vedere una bella cosa?

- Cos’è?

- Una bella cosa. Vieni a vedere. Presto.

- Dimmi cosa.

- Te la regalo. Ti regalo una bella cosa.

- Ho i piatti da lavare. Poi viene la signora, e non mi trova.

- La vuoi o non la vuoi? Alé, vieni.

- Aspetta lì, - disse Maria-nunziata, e chiuse la finestra.

Quando uscì dalla porticina di servizio, il ragazzo-giardiniere era sempre lì che bagnava i nasturzi.

- Ciao, - disse Maria-nunziata.

Maria-nunziata sembrava più alta perché aveva le scarpe belle coi sugheri, che era un peccato tenerle anche per i servizi, come piaceva a lei. Ma aveva una faccia bambina, piccola in mezzo al riccio dei capelli neri, e anche le gambe ancora magre e bambine, mentre il corpo, negli sbuffi del grembiule, era già pieno e adulto. E rideva sempre: a ogni cosa detta dagli altri o da lei, rideva.

- Ciao, - disse il ragazzo-giardiniere. Aveva la pelle marrone, sulla faccia, sul collo, sul petto: forse perché stava sempre così, mezzo nudo.

- Come ti chiami? - disse Maria-nunziata.

- Libereso, - disse il ragazzo-giardiniere.

Maria-nunziata rideva e ripetè: - Libereso… Libereso… che nome, Libereso.

- É un nome in esperanto, - disse lui. - Vuol dire libertà, in esperanto.

- Esperanto, - disse Maria-nunziata. - Sei esperanto, tu?

- L’esperanto è una lingua, - spiegò Libereso. Mio padre parla esperanto.

- Io sono calabrese, - disse Maria-nunziata.

- Come ti chiami?

- Maria-nunziata, - e rideva.

- Perchè ridi sempre?

- Ma perchè ti chiami Esperanto?

- Non esperanto: Libereso.

- Perchè?

- E perchè tu ti chiami Maria-nunziata?

- É il nome della Madonna. Io mi chiamo come la Madonna e mio fratello come san Giuseppe.

- Sangiuseppe?

Maria-nunziata scoppiava dal ridere: - Sangiuseppe! Giuseppe, non Sangiuseppe! Libereso!

- Mio fratello, - disse Libereso, - si chiama Germinal e mia sorella Omnia.

- Quella cosa, - disse Maria-nunziata, - fammi vedere quella cosa.

- Vieni, - disse Libereso. Posò l’innaffiatoio e la prese per mano.

Maria-nunziata s’impuntò: - Dimmi cos’è, prima.

- Vedrai, - disse lui, - mi devi promettere che la terrai da conto.

- Me la regali?

- Sì, te la regalo. - L’aveva condotta nell’angolo vicino al muro del giardino. C’erano delle piante di dalia in vaso alte quanto loro.

- É lì.

- Cosa?

- Aspetta.

Maria-nunziata faceva capolino dietro le sue spalle. Libereso si chinò per spostare un vaso, ne alzò un altro, vicino al muro, e indicò per terra.

- Lì, - disse.

- Cosa? - disse Maria-nunziata. Non vedeva niente: era un angolo in ombra, con foglie umide e terriccio.

- Guarda che si muove, - disse il ragazzo. Allora lei vide una pietra di foglie che si muoveva, una cosa umida, con occhi e piedi: un rospo.

- Mammamia!

Maria-nunziata era scappata saltando tra le dalie con le scarpe belle di sughero. Libereso era accoccolato vicino al rospo e rideva, con i denti bianchi in mezzo alla faccia marrone.

- Hai paura! É un rospo! Perché hai paura?

- É un rospo! - gemette Maria-nunziata.

- É un rospo. Vieni, - disse Libereso.

Lei gli puntò contro un dito: - Uccidilo.

Il ragazzo mise le mani avanti, quasi a ripararlo: - Non voglio. È buono.

- É un rospo buono?

- Sono tutti buoni. Mangiano i vermi.

- Ah, - disse Maria-nunziata, ma non s’avvicinava. Si mordeva il colletto del grembiule e cercava di vedere torcendo gli occhi.

- Guarda che bello, - disse Libereso e mise giù la mano.

Maria-nunziata s’avvicinò: non rideva più, guardava a bocca aperta: - No! Non lo toccare!

Libereso con un dito stava carezzando il rospo sulla schiena verde-grigia, piena di verruche bavose.

- Sei matto? Non sai che brucia, a toccarlo, e ti fa gonfiare la mano?

Il ragazzo le mostrò le sue grosse mani marrone, con le palme rivestite da uno strato giallo calloso.

- A me non fa niente, - disse. - É così bello.

Aveva preso il rospo per la collottola come fosse un gattino e se l’era posato sul palmo d’una mano. Maria-nunziata, mordendosi il collarino del grembiule, s’avvicinò e gli s’accoccolò vicino.

- Mammamia che impressione, - disse.

Erano accoccolati tutt’e due dietro le dalie, e i ginocchi rosa di Maria-nunziata sfioravano quelli marrone tutti sbucciature di Libereso. Libereso passava una mano sul dorso del rospo, di palma e di dorso, e ogni tanto lo riacchiappava quando voleva scivolar giù.

- Carezzalo anche tu, Maria-nunziata, - disse.

La ragazza si nascose le mani in grembo.

- No, - disse.

- Come? - lui disse, - non lo vuoi?

Maria-nunziata abbassò gli occhi, poi guardò il rospo e li riabbassò subito.

- No, - disse.

- É tuo. Te lo regalo, - disse Libereso.

Maria-nunziata aveva gli occhi annuvolati, adesso: era triste rinunciare a un regalo, nessuno le faceva mai regali, ma il rospo proprio le metteva schifo.

- Te lo lascio portare in casa, se vuoi. Ti terrà compagnia.

- No, - disse. Libereso rimise in terra il rospo che s’andò subito ad acquattare tra le foglie.

- Ciao, Libereso.

- Aspetta.

- Devo finire di lavare i piatti. La signora non vuole che esca in giardino.

- Aspetta. Ti voglio regalare qualcosa. Una cosa proprio bella. Vieni.

Lei si mise a seguirlo per i vialetti di ghiaia. Era uno strano ragazzo, Libereso, con i capelli lunghi e che pigliava in mano i rospi.

- Quanti anni hai, Libereso?

- Quindici. E tu?

- Quattordici.

- Compiti o da compire?

- Li compio il giorno dell’Annunciazione.

- É già passato?

- Come, non sai quand’è l’Annunciazione?

S’era rimessa a ridere.

- No.

- L’Annunciazione, quando c’è la processione. Non ci vai alla processione?

- Io no.

- Al mio paese sì che ci sono delle belle processioni. Al mio paese non è come qui. Ci sono grandi campi tutti di bergamotti e nient’altro che bergamotti. E tutto il lavoro è raccogliere bergamotti da mattino a sera. E noi eravamo quattordici fratelli e sorelle, e tutti raccoglievamo bergamotti, e cinque sono morti bambini, e a mia madre venne il tetano, e noi siamo stati in treno una settimana per venire da zio Carmelo e lì si stava in otto a dormire in un garage. Di’, perché porti i capelli così lunghi?

Si erano fermati a un’aiuola di calle.

- Perché così. Anche tu li hai lunghi.

- Io sono una femmina. Se li porti lunghi sei come una femmina.

- Io non sono come una femmina. Non è dai capelli che si vede se uno è maschio o femmina.

- Come non è dai capelli?

- Non è dai capelli.

- Perché non è dai capelli?

- Vuoi che ti regali una bella cosa?

- Sì.

Libereso si mise a girare tra le calle. Erano tutte sbocciate, le bianche trombe al cielo. Libereso guardava dentro ogni calla, ci frugava dentro con due dita e si nascondeva qualcosa nella mano stretta a pugno. Maria-nunziata non era entrata nell’aiuola e lo guardava ridendo in silenzio. Cosa faceva Libereso? Ormai aveva passato in rivista tutte le calle. Venne tendendo avanti le mani una nell’altra.

- Apri le mani, - disse. Maria-nunziata tese le mani a conca ma aveva paura a metterle sotto le sue.

- Che hai lì dentro?

- Una bella cosa. Vedrai.

- Fammi vedere, prima.

Libereso schiuse le sue mani e la lasciò guardare dentro. Aveva le mani piene di cetonie: cetonie di tutti i colori. Le più belle erano le verdi, poi ce n’erano di rossicce e di nere, e una anche turchina. E ronzavano, scivolavano una sulla corazza dell’altra e ruotavano le zampine nere in aria. Maria-nunziata si nascose le mani sotto il grembiule.

- Tieni, - disse Libereso, - non ti piacciono?

- Sì, - disse Maria-nunziata, ma teneva sempre le mani sotto il grembiule.

- A stringerle in mano fanno il solletico: vuoi sentire? Maria-nunziata tese avanti le mani, timidamente, e Libereso ci fece scendere quella cascatella d’insetti di tutti i colori.

- Coraggio. Non mordono.

- Mammamia! - Non aveva pensato che potessero morderla. Aprì le mani e le cetonie lasciate andare in aria aprirono le ali e i bei colori scomparvero e ci fu solo uno sciame di coleotteri neri che volavano e si posavano sulle calle.

- Peccato; io voglio farti un regalo e tu non vuoi.

- Devo andare a rigovernare. Se la signora non mi trova, poi grida.

- Non lo vuoi un regalo?

- Cosa mi regali?

- Vieni.

Continuava a condurla per mano tra le aiuole.

- Devo tornare presto in cucina, Libereso. Poi devo spennare una gallina.

- Puah!

- Perché: puah?

- Noi non mangiamo carne di animali morti.

- Sempre quaresima, fate?

- Come?

- Cosa mangiate?

- Tante cose, carciofi, lattuga, pomodori. Mio padre non vuole che si mangi la carne degli animali morti. E neanche caffè e zucchero.

- E lo zucchero della tessera?

- Lo vendiamo alla borsa nera.

Erano arrivati a una cascata di piante grasse, tutta stellata di fiori rossi.

- Bei fiori, - disse Maria-nunziata. - Ne prendi mai?

- Per fare?

- Per portarli alla Madonna. I fiori servono per portare alla Madonna.

- Mesembrianthemum.

- Cosa?

- Si chiama Mesembrianthemum, questa pianta, in latino. Tutte le piante si chiamano in latino.

- Anche la Messa è in latino.

- Non so.

Libereso stava sbirciando tra il serpeggiare dei rami sulla parete.

- Ecco là, - disse.

- Cos’è?

C’era un ramarro, fermo al sole, verde con disegnini neri.

- Ora lo piglio.

- No.

Ma lui s’avvicinava al ramarro a mani aperte, piano piano, poi uno scatto: acchiappato. Ora rideva contento con il suo riso bianco e marrone. - Guarda che mi scappa!

- Dalle mani chiuse ora sgusciava la testina smarrita, ora la coda. Anche Maria-nunziata rideva, ma faceva dei salti all’indietro ogni volta che vedeva il ramarro, e si stringeva la sottana tra i ginocchi.

- Insomma, non vuoi proprio che ti regali nulla? - disse Libereso, un po’ mortificato, e piano piano posò su un muretto il ramarro che saettò via: Maria-nunziata teneva gli occhi bassi.

- Vieni con me, - disse Libereso e la riprese per mano.

- A me piacerebbe avere un tubetto di rossetto, e dipingermi le labbra alla domenica per andare a ballare. E poi un velo nero per mettermi sulla testa, dopo, quando si va alla benedizione.

- Alla domenica, - disse Libereso, - vado al bosco con mio fratello e riempiamo due sacchi di pigne. Poi, alla sera, mio padre legge forte dei libri di Eliseo Reclus. Mio padre ha i capelli lunghi fin sulle spalle e la barba fino al petto. E porta i calzoni corti, estate e inverno. E io faccio dei disegni per la vetrinetta della FAI. E quelli col cilindro sono i finanzieri, quelli col cheppì i generali, e quelli col cappello tondo i preti. Poi ci do i colori all’acquarello.

C’era la vasca e tonde foglie di ninfea che galleggiavano.

- Zitta, - fece Libereso.

Sott’acqua si vide la rana che veniva su con scatti e abbandoni delle braccia verdi. A galla, saltò su una foglia di ninfea e ci si sedette in mezzo.

- Ecco, - fece Libereso, e calò una mano per acchiapparla, ma Maria-nunziata fece: - Uh! - e la rana saltò in acqua. Ora Libereso cercava ancora col naso a fior d’acqua.

- Laggiù.

Cacciò sotto una mano e la tirò fuori chiusa a pugno.

- Due in una volta, - disse. - Guarda. Sono due una sopra l’altra.

- Perché, - disse Maria-nunziata.

- Maschio e femmina appiccicati, - disse Libereso, -guarda come fanno.

E voleva mettere le rane in mano a Maria-nunziata. Maria-nunziata non sapeva se aveva paura perché erano rane o perché erano maschio e femmina appiccicati.

- Lasciali stare, - disse, - non bisogna toccare.

- Maschio e femmina, - ripeté Libereso. - Poi fanno i girini.

Una nuvola passava sopra il sole. Improvvisamente Maria-nunziata si disperò.

- É tardi. Certo la signora mi sta cercando.

Ma non se ne andava. Continuavano a girare per il giardino, e non c’era più sole. Fu la volta d’una biscia. Era dietro una siepe di bambù, una piccola biscia, un orbettino. Libereso se la fece arrotolare a un braccio e le carezzava la testina.

- Una volta ammaestravo le bisce, ne avevo una decina, anche una lunga lunga e gialla, di quelle d’acqua. Poi ha cambiato la pelle ed è scappata. Guarda questa che apre la bocca, guarda la lingua tagliata in due. Carezzala, non morde.

Ma Maria-nunziata aveva paura anche delle bisce. Allora andarono alla vaschetta di rocce. Prima le fece vedere gli zampilli, aprì tutti i rubinetti e lei era molto contenta. Poi le mostrò il pesce rosso. Era un vecchio pesce solitario, e già le squame cominciavano a imbianchire. Ecco: il pesce rosso piaceva a Maria-nunziata. Libereso cominciò a girare le mani in acqua per acchiapparlo, era una cosa difficile ma poi Maria-nunziata poteva metterlo in un vasetto e tenerlo anche in cucina. Lo prese, ma non lo tirò fuori dall’acqua per non farlo soffocare.

- Metti le mani giù, carezzalo, - disse Libereso, si sente che respira; ha le pinne come di carta e le scaglie che pungono, ma poco.

Ma Maria-nunziata non voleva carezzare neanche il pesce. In un’aiuola di petunie c’era del terriccio morbido e Libereso ci grattò con le dita e tirò fuori dei lombrichi lunghi lunghi e molli molli.

Maria-nunziata scappò con dei piccoli gridi.

- Poggia la mano qui, - disse Libereso indicando il tronco d’un vecchio pesco. Maria-nunziata non capiva ma ci mise la mano: poi gridò e corse ad immergerla nell’acqua della vasca. L’aveva tirata su piena di formiche.

Il pesco era tutto un va e vieni di formiche «argentine» piccolissime.

- Guarda, - disse Libereso e appoggiò una mano al tronco. Si vedevano le formiche che gli salivano su per la mano ma lui non si toglieva.

- Perché? - disse Maria-nunziata. - Perché ti riempi di formiche?

La mano era già nera, già le formiche gli salivano su per il polso.

- Leva la mano, - gemeva Maria-nunziata. - Ti fai montare tutte le formiche addosso.

Le formiche gli salivano sul braccio nudo, erano già al gomito. Ormai tutto il braccio era coperto da un velo di puntini neri che si muovevano; già le formiche gli arrivavano all’ascella ma lui non si scostava.

- Togliti, Libereso, butta il braccio in acqua!

Libereso rideva, qualche formica dal collo gli passava già alla faccia.

- Libereso! Tutto quello che vuoi! Prenderò tutti i regali che mi dài!

Gli buttò le braccia al collo, prese a strofinargli via le formiche.

Allora Libereso staccò la mano dall’albero, ridendo bianco e marrone, e si spolverò il braccio con noncuranza. Ma si vedeva che era rimasto commosso.

- Ebbene, ti farò un grande regalo, ho deciso. Il più gran regalo che posso farti.

- Cosa?

- Un porcospino.

- Mammamia… La signora! La signora che chiama!

Maria-nunziata aveva finito di rigovernare i piatti quando sentì battere un sassolino ai vetri della finestra. Sotto c’era Libereso con una grossa cesta.

- Maria-nunziata, fammi salire. Voglio farti una sorpresa.

- Non puoi salire. Cosa porti lì dentro?

Ma in quel momento la signora suonò e Maria-nunziata scomparve.

Quando tornò in cucina Libereso non c’era. Né dentro, né sotto la finestra. Maria-nunziata s’avvicinò all’acquaio. Allora vide la sorpresa. Su ogni piatto messo ad asciugare c’era un ranocchio che saltava, una biscia era arrotolata dentro una casseruola, c’era una zuppiera piena di ramarri, e lumache bavose lasciavano scie iridescenti sulla cristalleria. Nel catino pieno d’acqua nuotava il vecchio e solitario pesce rosso.

Maria-nunziata fece un passo indietro ma si vide tra i piedi un rospo, un grosso rospo. Anzi, doveva essere una femmina perché dietro le veniva tutta la nidiata, cinque rospettini in fila, che avanzavano a piccoli balzi sulle piastrelle bianche e nere.



## Un bastimento carico di granchi {-}

Il primo bagno dell’anno i ragazzi di Piazza dei Dolori lo fecero una domenica d’aprile, col cielo azzurro nuovo nuovo e un sole allegro e giovane. Scesero correndo per i carrugi sventolando le brachette di maglia rattoppate, qualcuno ciabattando già in zoccoli per l’acciottolato, i più senza calze, per non dover faticare a rimettersele sui piedi bagnati. Corsero al molo saltando le reti che si dilungavano per terra e s’alzavano sui piedi nudi e callosi dei pescatori acculati a rammendarle. Tra gli scogli della massicciata si spogliarono, contenti di quell’odore agro di vecchie alghe marcite e di quel volare di gabbiani che cercava di riempire il cielo troppo grande. I vestiti e le scarpe li nascosero nei cavi degli scogli suscitando fughe di giovani granchi; e cominciarono a saltare scalzi e spogliati da uno scoglio all’altro aspettando che uno si decidesse a tuffarsi per primo.

L’acqua era calma ma non limpida, di un denso azzurro con riflessi verdi crudi. Gian Maria detto Mariassa salì in cima a uno scoglio alto e soffiò col pollice sotto il naso in quel suo gesto da pugile.

- Alé, - disse; giunse le mani avanti e si tuffò di testa. Uscì qualche metro più in là, sputando a zampillo e facendo il morto.

- Fredda? - gli chiesero.

- Caldissima, - gridò e si mise a dar bracciate furiose per non gelare.

- Banda! Con me! - disse Cicin che faceva conto d’essere il capo sebbene nessuno gli desse mai retta.

Si tuffarono tutti: Pier Lingera che fece la capriola, Bombolo che prese la panciata, Paulò, Carruba, e per ultimo Menin che dell’acqua aveva una paura maledetta e si tuffò di piedi tenendosi il naso tappato con le dita.

In acqua Pier Lingera che era il più forte fece bere tutti uno per volta, poi tutti si misero d’accordo e insieme fecero bere Pier Lingera.

Allora Gian Maria detto Mariassa propose: - La nave! Andiamo sulla nave!

C’era ancora il bastimento attraverso al porto, affondato durante la guerra dai tedeschi per ostruirlo. Anzi ce n’erano due uno sopra l’altro, quello che si vedeva poggiava sopra uno tutto sommerso.

- Alé, - dissero gli altri.

- Si può montarci sopra? - chiese Menin. - É minato.

- Balle: minato! - disse Carruba. - Quelli dell’Arenella ci montano quando vogliono e ci giocano alla guerra.

Si misero a nuotare verso la nave.

- Banda! Con me! - disse Cicin che voleva fare il capo: ma gli altri andavano più forte di lui e lo lasciarono indietro, eccetto Menin che nuotava a rana ed era sempre l’ultimo.

Arrivarono sotto e il bastimento alzava le murate nere di vecchio catrame, nude e muffite, con le sovrastrutture smantellate contro il cielo azzurro nuovo. Una barba d’alghe putride saliva a ricoprirlo su dalla chiglia e la vecchia vernice si scrostava a grandi segmenti: i ragazzi gli girarono tutt’intorno, poi rimasero sotto la poppa a guardare il nome tutto cancellato: “Abukir, Egypt”. C’era la catena dell’ancora, tesa obliqua che ogni tanto oscillava alle acquate della marea, scricchiolando negli enormi anelli rugginosi.

- Non saliamo, - disse Bombolo.

- Ma va’, - fece Pier Lingera e già s’era attaccato alla catena, mani e piedi. S’arrampicò come una scimmia e gli altri lo seguirono.

Bombolo a metà scivolò e ribatté di pancia in mare; Menin non riusciva a salire e dovettero venire in due a tirarlo.

A bordo cominciarono a girare in silenzio, per quella nave smantellata, si misero a cercare la ruota del timone, la sirena, i boccaporti, le scialuppe, tutte quelle cose che ci dovevano essere su una nave. Ma questa era una nave squallida come una zattera, coperta solo di sterco bianchiccio di gabbiano. Ce n’erano cinque, di gabbiani, appoggiati a una murata; a sentire i passi scalzi della masnada s’alzarono a volo uno dopo l’altro con gran sbattere d’ali.

- Uhà! - fece il verso Paulò e tirò dietro all’ultimo un bullone raccattato.

- Banda: andiamo dalle macchine! - disse Cicin. Certo giocare in mezzo ai macchinari o nella stiva sarebbe stato più bello.

- Si potrà scendere alla nave che c’è sotto? - chiese Carruba. Questo sarebbe stato bellissimo: stare là sotto, tutti chiusi, con il mare intorno e sopra come in un sottomarino.

- Quella di sotto è minata! - disse Menin.

- Sei tu, minato! - gli dissero.

Presero giù da una scaletta. Fatti pochi gradini si fermarono: ai loro piedi cominciava l’acqua nera, e sciabordava nel chiuso. I ragazzi di Piazza dei Dolori guardavano fermi e in silenzio; in fondo a quell’acqua, un luccichio nero di aculei: colonie di ricci che divaricavano lenti le spine. E le pareti tutt’intorno erano incrostate di patelle dal guscio barbuto d’alghe verdi, abbarbicate al ferro delle pareti che sembrava roso. E c’era un brulicare di granchi ai margini dell’acqua, migliaia di granchi di tutte le forme e di tutte le età che ruotavano sulle zampe curve e raggiate, e digrignavano le chele, e sporgevano gli occhi senza sguardo. Il mare sciacquava sordo nel quadrato delle mura di ferro, lambendo quelle piatte pance di granchio. Forse tutta la stiva della nave era piena di granchi brancolanti e un giorno la nave si sarebbe mossa sulle zampe dei granchi e avrebbe camminato per il mare.

Risalirono sopracoperta, a prua. Allora videro la bambina. Non l’avevano vista prima, pure sembrava fosse sempre stata lì. Era una bambina sui sei anni, grassa, con i capelli lunghi e ricci. Era tutta abbronzata e aveva indosso solo le mutandine bianche. Non si capiva da che parte fosse arrivata. Non li guardò nemmeno. Era tutta attenta a una medusa capovolta sull’impiantito di legno, con i festoni mollicci dei tentacoli sparpagliati intorno. La bambina con uno stecco cercava di rimetterla con la calotta in alto.

I ragazzi di Piazza dei Dolori le si fermarono intorno, a bocca aperta. Mariassa si fece avanti per primo. Tirò su dal naso.

- Chi sei? - disse.

La bambina alzò gli occhi celesti nella faccia paffuta e scura; poi riprincipiò a far leva con lo stecco sotto la medusa.

- Dev’essere della banda dell’Arenella, - disse Carruba che era pratico.

I ragazzi dell’Arenella avevano delle bambine che venivano con loro a nuotare e a giocare al pallone, e anche a far la guerra con le canne.

- Tu, - disse Mariassa, - sei nostra prigioniera.

- Banda! - fece Cicin. - Prendetela viva!

La bambina continuava a manovrare la medusa.

- Allarmi! - gridò Paulò che s’era voltato indietro per caso. - La banda dell’Arenella! Mentre loro stavano attenti alla bambina, i ragazzi dell’Arenella che passavano in acqua le giornate erano arrivati nuotando sott’acqua, erano saliti in silenzio per la catena dell’ancora, erano apparsi scavalcando quatti le murate. Erano ragazzi bassi e tarchiati, soffici come gatti, coi capelli rasi, la pelle scura. Le loro brache non erano nere e lunghe e cascanti come quelle dei ragazzi dei Dolori, ma fatte solo di una striscia di tela bianca.

Cominciò la lotta; i ragazzi di Piazza dei Dolori erano magri e tutti nervi, tranne Bombolo che era un pancione, ma avevano una rabbia fanatica nel picchiarsi, agguerrita dalle lunghe zuffe nei piccoli carrugi della città vecchia contro le bande di San Siro e dei Giardinetti. Quelli dell’Arenella ebbero il sopravvento in principio per via della sorpresa, ma poi quelli dei Dolori si abbarbicarono alle scalette e di lì non ci fu verso di spostarli, perché non volevano a nessun costo lasciarsi trasportare alle murate, dove era facile farsi sbattere a bagno. Alla fine Pier Lingera che era più forte dei compagni e anche più vecchio, e veniva con loro solo perché era ripetente, riuscì a far arretrare uno dell’Arenella fino ai bordi e a spingerlo giù in mare.

Allora quelli dei Dolori passarono all’offensiva: quelli dell’Arenella, che si sentivano più nel loro in acqua e, gente pratica, non avevano puntigli d’onore per la testa, uno dopo l’altro sfuggirono ai nemici e si tuffarono.

- Venite a prenderci in acqua, se avete coraggio, -gridarono.

- Banda! Con me! - urlò Cicin e già stava per tuffarsi.

- Sei scemo? - lo trattiene Mariassa. - In acqua l’hanno vinta come vogliono! - E prese a gridare insolenze ai fuggiaschi.

Quelli dell’Arenella cominciarono a tirare acqua da sotto; e la tiravano tanto forte che non c’era posto sulla nave dove non arrivassero le loro acquate. Alla fine si stancarono e presero il largo a testa bassa e braccia arcuate, rialzandosi ogni tanto per respirare con piccoli schizzi.

Quelli di Piazza dei Dolori erano rimasti padroni del campo. Andarono a prua: la bambina era sempre lì. Era riuscita a voltare la medusa e ora cercava di sollevarla sullo stecco.

- Ci hanno lasciato un ostaggio! - fece Mariassa.

- Banda! Un ostaggio! - s’eccitò Cicin.

- Vigliacchi! - gridò Carruba dietro ai fuggiaschi. -Lasciare le donne in mano ai nemici!

Avevano un senso dell’onore molto spiccato, a Piazza dei Dolori.

- Vieni con noi, - disse Mariassa e fece per metterle una mano su una spalla.

La bambina gli fece cenno di star fermo: stava per riuscire a sollevare la medusa. Mariassa si chinò a guardare. Allora la bambina tirò su lo stecco, con la medusa in bilico sopra, lo tirò su, lo tirò su, sbattè la medusa in faccia a Mariassa.

- Porca! - gridò Mariassa sputando e premendosi la faccia.

La bambina guardava tutti e rideva. Poi si voltò, andò proprio in cima alla prua, alzò le braccia congiungendo la punta delle dita, si tuffò ad angelo, e nuotò via senza voltarsi. I ragazzi di Piazza dei Dolori non si erano mossi.

- Di’, - chiese Mariassa, palpandosi una guancia. - É vero che le meduse fanno bruciare tutta la pelle?

- Aspetta e lo saprai, - fece Pier Lingera. - Però è meglio che ti tuffi subito.

- Alè, - disse Mariassa, avviandosi con gli altri.

Poi si fermò: - D’ora in avanti dobbiamo avere una donna anche noi nella banda! Menin! Farai venire tua sorella!

- Mia sorella è scema, - disse Menin.

- Non importa, - disse Mariassa, - alè, - e diede uno spintone a Menin buttandolo a mare, perchè tanto a tuffarsi non era capace. Poi si tuffarono tutti.


## Il giardino incantato {-}

Giovannino e Serenella camminavano per la strada ferrata. Giù c’era un mare tutto squame azzurro cupo azzurro chiaro; su, un cielo appena venato di nuvole bianche. I binari erano lucenti e caldi che scottavano. Sulla strada ferrata si camminava bene e si potevano fare tanti giochi: stare in equilibrio lui su un binario e lei sull’altro e andare avanti tenendosi per mano, oppure saltare da una traversina all’altra senza posare mai il piede sulle pietre. Giovannino e Serenella erano stati a caccia di granchi e adesso avevano deciso di esplorare la strada ferrata fin dentro la galleria. Giocare con Serenella era bello. perchè non faceva come tutte le altre bambine che hanno sempre paura e si mettono a piangere a ogni dispetto: quando

Giovannino diceva: - Andiamo là, - Serenella lo seguiva sempre senza discutere.

Deng! Sussultarono e guardarono in alto. Era il disco di uno scambio ch’era scattato in cima a un palo. Sembrava una cicogna di ferro che avesse chiuso tutt’a un tratto il becco. Rimasero un po’ a naso in su a guardare: che peccato non aver visto! Ormai non lo faceva più.

- Sta per venire un treno, - disse Giovannino.

Serenella non si mosse dal binario. - Da dove? chiese.

Giovannino si guardò intorno, con aria d’intender sene.

Indicò il buco nero della galleria che appariva ora limpido ora sfocato, attraverso il tremito del vapore invisibile che si levava dalle pietre della strada.

- Di lì, - disse. Sembrava già di sentirne lo sbuffo incupito dalla galleria e vederselo tutt’a un tratto addosso, scalpitante fumo e fuoco, con le ruote che mangiavano i binari senza pietà.

- Dove andiamo, Giovannino?

C’erano grandi agavi grige, verso mare, con raggere di aculei impenetrabili. Verso monte correva una siepe di ipomea, stracarica di foglie e senza fiori. Il treno non si sentiva ancora: forse correva a locomotiva spenta senza rumore e sarebbe balzato su di loro tutt’a un tratto. Ma già Giovannino aveva trovato un pertugio nella siepe. - Di là.

La siepe sotto il rampicante era una vecchia rete metallica cadente.

In un punto, s’accartocciava su da terra come un angolo di pagina. Giovannino era già sparito per metà e sgusciava dentro.

- Dammi una mano, Giovannino!

Si ritrovarono in un angolo di giardino, tutt’e due carponi in un’aiola, coi capelli pieni di foglie secche e di terriccio. Tutto era zitto intorno; non muoveva una foglia.

- Andiamo, - disse Giovannino e Serenella disse: - Sì.

C’erano grandi e antichi eucalipti color carne, e vialetti di ghiaia. Giovannino e Serenella camminavano in punta di piedi pei vialetti, attenti al fruscio della ghiaia sotto i passi. E se adesso arrivassero i padroni?

Tutto era così bello: volte strette e altissime di foglie ricurve d’eucalipto e ritagli di cielo; restava solo quell’ansia dentro, del giardino che non era loro e da cui forse dovevano esser cacciati tra un momento. Ma nessun rumore si sentiva. Da un cespo di corbezzolo, a una svolta, s’alzò un volo di passeri, con gridi. Poi ritornò silenzio. Era forse un giardino abbandonato?

Ma l’ombra dei grandi alberi a un certo punto finiva e si trovarono sotto il cielo aperto, di fronte ad aiole tutte ben ravviate di petunie e convolvoli, e viali e balaustrate e spalliere di bosso. E sull’alto del giardino, una grande villa coi vetri lampeggianti e tende gialle e arancio.

E tutto era deserto. I due bambini venivano su guardinghi calpestando ghiaia: forse le vetrate stavano per spalancarsi tutt’a un tratto e signori e signore severissimi per apparire sui terrazzi e grossi cani per essere sguinzagliati per i viali. Trovarono vicino a una cunetta una carriola. Giovannino la prese per le staffe e la spinse innanzi: aveva un cigolo, a ogni giro di ruota, come un fischio. Serenella ci si sedette sopra e avanzavano zitti, Giovannino spingendo la carriola con lei sopra, fiancheggiando le aiole e i giochi d’acqua.

- Quello, - diceva Serenella a bassa voce di tanto in tanto, indicando un fiore. Giovannino poggiava e andava a strapparlo e glielo dava. Ne aveva già dei belli in un mazzetto. Ma scavalcando le siepi per scappare, forse li avrebbe dovuti buttar via!

Così arrivarono a uno spiazzo e finiva la ghiaia e c’era un fondo di cemento e mattonelle. E in mezzo a questo spiazzo s’apriva un grande rettangolo vuoto: una piscina. Ne raggiunsero i margini: era a piastrelle azzurre, ricolma d’acqua chiara fino all’orlo.

- Ci tuffiamo? - chiese Giovannino a Serenella. Certo doveva essere assai pericoloso se lui chiedeva a lei e non diceva soltanto: - Giù! - Ma l’acqua era così limpida e azzurra e Serenella non aveva mai paura. Scese dalla carriola e vi depose il mazzolino. Erano già in costume da bagno: erano stati a cacciar granchi fino allora. Giovannino si tuffò: non dal trampolino perché il tonfo avrebbe fatto troppo rumore, ma dall’orlo. Andò giù giù a occhi aperti e non vedeva che azzurro, e le mani come pesci rosa; non come sotto l’acqua del mare, piena d’ombre informi verdi-nere. Un’ombra rosa sopra di sé: Serenella! Si presero per mano e riaffiorarono all’altro capo, un po’ con apprensione. No, non c’era proprio nessuno ad osservarli. Non era bello come s’immaginavano: rimaneva sempre quel fondo d’amarezza e d’ansia, che tutto questo non spettava loro e potevano esserne di momento in momento, via, scacciati.

Uscirono dall’acqua e proprio lì vicino alla piscina trovarono un tavolino col ping-pong. Giovannino diede subito un colpo di racchetta alla palla: Serenella fu svelta dall’altra parte a rimandargliela. Giocavano così, dando bòtte leggere perché da dentro alla villa non sentissero. A un tratto un tiro rimbalzò alto e Giovannino per pararlo fece volare la palla via lontano; batté sopra un gong sospeso tra i sostegni d’una pergola, che vibrò cupo e a lungo. I due bambini si rannicchiarono dietro un’aiola di ranuncoli. Subito arrivarono due servitori in giacca bianca, reggendo grandi vassoi, posarono i vassoi su un tavolo rotondo sotto un ombrellone a righe gialle e arancio e se ne andarono.

Giovannino e Serenella s’avvicinarono al tavolo. C’era tè, latte e pan-di-Spagna. Non restava che sedersi e servirsi. Riempirono due tazze e tagliarono due fette. Ma non riuscivano a stare ben seduti, si tenevano sull’orlo delle sedie, muovendo le ginocchia. E non riuscivano a sentire il sapore dei dolci e del tè e latte. Ogni cosa in quel giardino era così: bella e impossibile a gustarsi, con quel disagio dentro e quella paura, che fosse solo per una distrazione del destino, e che presto sarebbero chiamati a darne conto.

Quatti quatti, si avvicinarono alla villa. Di tra le stecche d’una persiana a griglia videro, dentro, una bella stanza ombrosa con collezioni di farfalle alle pareti. E in questa stanza c’era un pallido ragazzo. Doveva essere il padrone della villa e del giardino, lui fortunato. Era seduto su una sedia a sdraio e sfogliava un grosso libro con figure. Aveva mani sottili e bianche e un pigiama accollato benché fosse estate.

Ora, ai due bambini, spiandolo tra le stecche, si spegneva a poco a poco il batticuore. Infatti quel ragazzo ricco sembrava sedesse e sfogliasse quelle pagine e si guardasse intorno con più ansia e disagio di loro. E s’alzasse in punta di piedi come se temesse che qualcuno, di momento in momento, potesse venire a scacciarlo, come se sentisse che quel libro, quella sedia a sdraio, quelle farfalle incorniciate ai muri e il giardino coi giochi e le merende e le piscine e i viali, erano concessi a lui solo per un enorme sbaglio, e lui fosse impossibilitato a goderne, ma solo provasse su di sé l’amarezza di quello sbaglio, come una sua colpa.

Il ragazzo pallido girava per la sua ombrosa stanza con passi furtivi, accarezzava i margini delle vetrine costellate di farfalle con le bianche dita, e si fermava in ascolto. A Giovannino e Serenella il batticuore spento riprendeva ora più fitto. Era la paura di un incantesimo che gravasse su quella villa e quel giardino, su tutte quelle cose belle e comode, come un’antica ingiustizia commessa.

Il sole s’oscurò di nuvole. Zitti zitti Giovannino e Serenella se ne andarono. Rifecero la strada pei vialetti, di passo svelto, ma senza mai correre. E traversarono carponi quella siepe. Tra le agavi trovarono un sentiero che portava alla spiaggia, breve e sassosa, con cumuli d’alghe che seguivano la riva del mare. Allora inventarono un gioco bellissimo: battaglia con le alghe. Se ne tirarono manciate in faccia uno con l’altra fino a sera. C’era di buono che Serenella non piangeva mai.