# Prima che tu dica «Pronto» {-}

Apologhi e racconti 1943–1958


## L’uomo che chiamava Teresa {-}

Scesi dal marciapiede, feci qualche passo a ritroso guardando in su, e, giunto in mezzo alla via, portai le mani alla bocca, a megafono e gridai verso gli ultimi piani del palazzo: – Teresa!

La mia ombra si spaventò della luna e mi si rannicchiò tra i piedi.

Passò uno. Io chiamai ancora: – Teresa! – Quello s’avvicinò, disse: – Se non chiamate più forte non vi sente. Proviamo in due. Allora: conto fino a tre, al tre attacchiamo insieme –. E disse: – Uno, due, tre –. E insieme gridammo: – Tereeesaaa!

Passò un gruppetto d’amici che tornavano dal teatro o dal caffè e videro noi due che chiamavamo. Dissero: – Su, che vi diamo una voce anche noi –. E anche loro vennero in mezzo alla strada e quello di prima diceva uno due tre e allora tutti in coro si gridava: – Te-reee-saaa!

Passò ancora qualcuno e si unì a noi; dopo un quarto d’ora eravamo radunati in parecchi, una ventina, quasi. E ogni tanto arrivava qualcuno nuovo.

Metterci d’accordo per gridare bene, tutti insieme, non fu facile. C’era sempre qualcuno che cominciava prima del tre o che tirava troppo in lungo, ma alla fine si riusciva a fare già qualcosa di ben fatto. Si convenne che – Te – andava detto basso e lungo, – re – acuto e lungo, – sa – basso e breve. Veniva molto bene. Poi ogni tanto qualche litigio per qualcuno che stonava.

Già si cominciava ad essere affiatati, quando uno, che, a giudicare dalla voce, doveva avere la faccia piena di lentiggini, chiese: – Ma siete proprio sicuro che sia in casa?

– Io no – risposi.

– Brutt’affare – disse un altro. – Dimenticato la chiave, vero?

– Per quello – dissi – io la chiave ce l’ho.

– Allora – mi si chiese – perché non salite?

– Ma io non sto mica qui – risposi. – Sto dall’altra parte della città.

– Ma, allora, scusate la curiosità – chiese circospetto quello con la voce piena di lentiggini – qui chi ci sta?

– Non saprei davvero – dissi.

Ci fu un po’ di malcontento intorno.

– Ma si può sapere allora – chiese uno con la voce piena di denti – perché chiamate Teresa qua sotto?

– Per me – risposi – possiamo anche chiamare un altro nome, o in un altro posto. Per quel che costa.

Gli altri ci rimasero un po’ male.

– Non avete voluto mica farci uno scherzo? – chiese quello delle lentiggini, sospettoso.

– E che? – dissi, risentito e mi voltai verso gli altri a chieder garanzia delle mie intenzioni. Gli altri restarono in silenzio, mostrando di non aver raccolto l’insinuazione.

Ci fu un momento di disagio.

– Vediamo – disse uno, bonario. – Possiamo chiamare Teresa ancora una volta, poi ce ne andiamo a casa.

E si fece ancora una volta – uno due tre Teresa! – ma non riuscì tanto bene. Poi scantonammo, chi da una parte, chi dall’altra.

Ero già svoltato in piazza, quando mi parve di sentire ancora una voce che gridava: – Tee-reee-sa!

Qualcuno doveva esser rimasto a chiamare, ostinato.



## Il lampo {-}

Mi capitò una volta, a un crocevia, in mezzo alla folla, all’andirivieni.

Mi fermai, battei le palpebre: non capivo niente. Niente, niente del tutto: non capivo le ragioni delle cose, degli uomini, era tutto senza senso, assurdo. E mi misi a ridere.

Lo strano era per me allora che non me ne fossi mai accorto prima. E avessi fin’allora accettato tutto: semafori, veicoli, manifesti, divise, monumenti, quelle cose così staccate dal senso del mondo, come se ci fosse una necessità, una conseguenza che le legasse l’una all’altra.

Allora il riso mi morì in gola, arrossii di vergogna. Gesticolai, per richiamare l’attenzione dei passanti e – Fermatevi un momento! – gridai – c’è qualcosa che non va! Tutto è sbagliato! Facciamo cose assurde! Questa non può essere la strada giusta! Dove si va a finire?

La gente mi si fermò intorno, mi squadrava, curiosa. Io rimanevo lì in mezzo, gesticolavo, smaniavo di spiegarmi, di farli partecipi del lampo che m’aveva illuminato tutt’a un tratto: e restavo zitto. Zitto, perché nel momento in cui avevo alzato le braccia e aperto bocca, la grande rivelazione m’era stata come ringhiottita e le parole m’erano uscite così, per via dello slancio.

– Ebbene? – chiese la gente – cosa vuol dire? Tutto è al suo posto. Tutto va come deve andare. Ogni cosa è conseguenza d’un’altra. Ogni cosa è ordinata con le altre. Noi non vediamo niente d’assurdo o d’ingiustificato!

E io rimasi lì, smarrito, perché alla mia vista tutto era tornato al suo posto e tutto mi sembrava naturale, semafori, monumenti, divise, grattacieli, rotaie, mendicanti, cortei; e pure non me ne veniva tranquillità, ma tormento.

– Scusate – risposi – Forse ho sbagliato io. M’era sembrato. Ma tutto è a posto. Scusate – e mi feci largo tra i loro sguardi irti.

Pure, anche adesso, ogni volta (spesso) che mi accade di non capire qualche cosa, allora, istintivamente, mi prende la speranza che sia di nuovo la volta buona, e che io torni a non capire più niente, a impossessarmi di quella saggezza diversa, trovata e perduta nel medesimo istante.



## Chi si contenta {-}

C’era un paese dove era proibito tutto.

Ora, l’unica cosa non proibita essendo il gioco della lippa, i sudditi si riunivano in certi prati che erano dietro al paese e lì, giocando alla lippa, passavano le giornate.

E siccome le proibizioni erano venute un poco per volta, sempre per giustificati motivi, non c’era nessuno che trovasse a ridire o non sapesse adattarsi.

Passarono gli anni. Un giorno i connestabili videro che non c’era più ragione a che tutto fosse proibito e mandarono messi ad avvertire i sudditi che potevano fare quel che volevano.

I messi andarono in quei posti dove usavano riunirsi i sudditi.

– Sapete – annunziarono – non è più proibito niente.

Quelli continuavano a giocare alla lippa.

– Avete capito? – insistettero i messi. – Siete liberi di fare quel che volete.

– Bene – risposero i sudditi. – Noi giochiamo alla lippa.

I messi s’affannarono a ricordar loro quante occupazioni e belle e utili vi fossero cui loro avevano atteso in passato e cui potevano di nuovo attendere d’allora in poi. Ma quelli non davano retta e continuavano a giocare, una botta dopo l’altra, senza nemmeno prender fiato.

Visti vani i tentativi, i messi andarono a dirlo ai connestabili.

– Presto fatto – dissero i connestabili. – Proibiamo il gioco della lippa.

Fu la volta che il popolo fece la rivoluzione e li ammazzò tutti.

Poi senza perdere tempo, tornò a giocare alla lippa.



## Fiume asciutto {-}

Ora, io mi ritrovai nel fiume asciutto. Già da tempo mi teneva un paese non mio, ove le cose anzi che farmisi a poco a poco più familiari, sempre più mi apparivano come velate da insospettate differenze: e nelle forme e nei colori e nelle reciproche armonie. Altre da quelle che avevo imparato a conoscere mi circondavano ora colline, con delicate curvature di declivi, e i campi pure e le vigne andavano i quieti declivi seguendo e le terrazze erte, s’abbandonavano in docili pendenze. Tutti nuovi erano i colori, come toni di un arcobaleno sconosciuto. Gli alberi, sparsi, sembravano sospesi, come piccole nubi, e quasi trasparenti.

Allora io m’accorsi dell’aria, di come essa si faceva concreta al mio sguardo, e mi riempiva le mani come io le protendevo in essa. E vidi me impossibile a conciliare con il mondo intorno, scosceso e calcinoso com’ero io dentro e con squarci di colore d’una vivezza quasi cupa, come urli o risate. E per quanto m’ingegnassi a mettere parole tra me e le cose, non mi riusciva di trovarne d’adatte a rivestirle; perché tutte le mie parole erano dure e appena scheggiate: e il dirle era come posare tante pietre.

Pure, se in me si veniva disviluppando qualche sopita memoria, questa era di cose non vissute ma di apprese: forse paesi non creduti visti sul fondo di antiche pitture, forse parole di antichi poeti incompresi.

In una tale fluida atmosfera io vivevo si può dire nuotando e sentivo via via smussarmisi gli attriti ed io dissolvermi, assorbito in essa. Ma a ritrovar me stesso, bastò che m’incontrassi nel vecchio fiume asciutto.

Mi muoveva – era estate – un desiderio d’acqua, religioso, quasi di un rito. Mi disponevo, scendendo tra le vigne quella sera, a un bagno sacro e la parola acqua, già per me sinonimo di felicità, si dilatava nella mia mente come nome ora di dea ora di amante. Me ne apparve il tempio sul fondo della valle, dietro una pallida sponda di arbusti. Era un grande fiume di sassi bianchi, pieno di silenzio.

Solo vestigio d’acqua, un rivolo strisciava in disparte, quasi di nascosto. A tratti l’esiguità del rigagnolo, tra pietre grandi precludenti l’intorno e rive di canneti, mi ritrasportava tra i noti torrenti e mi riproponeva alla memoria più strette e faticate valli.

Fu questo: e forse anche il contatto delle pietre sotto i miei piedi – rosi sassi del fondo dal dorso incrostato d’un velo d’alghe rattrappite – o l’inevitabile muovere dei miei passi, a balzi, da l’uno scoglio all’altro, o forse fu solo un rumore che fece la ghiaia, franando.

Sta il fatto che il divario tra me e i luoghi qui scemò e si compose: una sorta di fratellanza come di metafisica consanguineità mi legava a quel pietrame, fecondo solo di timidi, tenacissimi licheni. E nel vecchio fiume asciutto riconobbi un mio antico padre ignudo.

Così, noi andavamo per il fiume asciutto. Colui che si muoveva con me era un compagno di sorte, uomo dei luoghi, cui l’oscurità della pelle e del pelame che gli scendeva a barbe fino dalla schiena, unita a la tumidezza delle labbra e al profilo camuso, conferiva un grottesco sembiante di capotribù non so meglio se congolese o oceàno. Presentava egli un fiero e gagliardo aspetto e nel viso ancorché occhialuto e nel procedere contrastato però dalla goffa sbracatura di quei bagnanti improvvisati che eravamo. Benché casto nella vita come un quacchero, era all’incontro osceno come un satiro nei discorsi. Il suo accento era quanto di più aspirato e fumigante mi fosse mai stato dato d’intendere: parlava egli a bocca eternamente spalancata o piena d’aria emettendo, a sfogo continuo del carattere sulfureo, uragani d’improperi mai uditi.

Tali, noi risalivamo il fiume asciutto in cerca d’un allargamento della vena dove lavare i nostri corpi, lordi e stanchi che erano.

Ora, a noi che camminavamo per il grande ventre, a un’ansa, lo sfondo s’arricchì di nuovi oggetti. Su alti scogli bianchi, avventura per gli sguardi, sedevano due, tre, forse quattro signorine, in costume da bagno. Costumi rossi e gialli – anche azzurri, è probabile, ma di questo non ricordo: solo di rosso e di giallo abbisognavano i miei occhi – e cuffiette, come in una spiaggia alla moda.

Fu come il canto di un gallo.

Un verde palmo d’acqua correva lì vicino e arrivava ai calcagni; loro per bagnarsi vi si accoccolavano.

Ci arrestammo, divisi tra la letizia della vista, il morso dei rimpianti ch’essa ci destava, e la vergogna di noi brutti e ingaglioffiti. Poi avanzammo verso di loro che stavano con indifferenza considerandoci e azzardammo qualche frase, studiandole, come suole, più spiritose e banali che potessimo. Il compagno sulfureo secondò il gioco senz’entusiasmo con una sorta di timido riserbo.

Sta il fatto che dopo poco, stanchi e del nostro faticoso dire e del freddo rispondere di quelle, ci rimettemmo in cammino, dando libero corso a più agevoli commenti. E, a consolarci, bastava, custodito negli occhi, quel ricordo più che di corpi, di costumi da bagno gialli e rossi.

Talora un braccio della corrente, non fonda, si spandeva allagando tutto l’alveo; e noi, alte e inaccessibili essendo le rive, lo traversavamo coi piedi nell’acqua. Portavamo scarpe leggere, di tela e gomma e l’acqua ci correva dentro: e quando si tornava nell’asciutto i piedi ci guazzavano dentro ad ogni passo, con sbuffi e sciacquio.

Imbruniva. Il pietrame bianco s’animava di punti neri, saltanti: i gerini.

Dovevano aver messo le zampe allora allora, piccoli e coduti che erano, e sembravano non essersi ancora ben capacitati di quella nuova forza che, tratto a tratto, li sbalestrava in aria. Ogni pietra ne aveva uno, ma per poco, che quello saltava e un altro succedeva al suo posto. E poi che simultanei erano i balzi e poi che procedendo per il grande fiume altro non si vedeva che il pullulare di quella moltitudine anfibia, avanzante come un esercito senza limiti, un senso di sgomento mi si faceva dentro, quasi quella sinfonia in bianco e nero, quel cartone animato triste come un disegno cinese, paurosamente rendesse l’idea dell’infinito.

Ci si fermò a uno specchio d’acqua che prometteva spazio bastante a immergere tutto il nostro corpo; anzi, ad allungare qualche bracciata. Io m’immersi scalzo e spogliato: era un’acqua vegetale, putrida per un lento sfacelo di piante fluviali. Il fondo era viscido e melmoso: e innalzava, a toccarlo, torbide nuvole fino alla superficie.

Pure, era acqua; ed era bella.

Il compagno scese in acqua con scarpe e calze, solo lasciando a riva gli occhiali. Poi, poco compreso del lato religioso della cerimonia, prese ad insaponarsi.

Cominciammo così quella giuliva festa che è il lavarsi, quando esso è raro e difficile. Il laghetto che ci conteneva appena traboccava di schiuma e di barriti, come per un bagno di elefanti.

Sulle prode del fiume erano salici e arbusti e case con ruote da molino; e tale era la loro irrealtà, in confronto alla concretezza di quell’acqua e di quelle pietre, che il grigio della sera, infiltrandosi, dava loro l’aspetto di un arazzo stinto.

Il compagno si lavava i piedi, ora, in strana guisa: senza scalzarsi e insaponandosi scarpe e calze addosso.

Poi, ci asciugammo e ci vestimmo. Da una mia calza, nel raccoglierla, saltò fuori un gerino.

Sugli occhiali del compagno, posati a riva, doveva esser arrivata un’acquata. E – come se li mise – così gaio dovette apparirgli lo scompiglio di quel mondo, colorato dagli ultimi sprazzi del tramonto, visto attraverso un paio di lenti bagnate, che prese a ridere, a ridere, senza freno e a me che ne chiedevo ragione disse: «Vedo tutto un puttanaio!»

E, più lindi, con una tiepida spossatezza in corpo, al posto della sorda stanchezza di prima, ci accomiatammo dal nuovo amico fiume e ci allontanammo per una stradella che seguiva la riva ragionando delle cose nostre e di quando v’avremmo fatto ritorno, e tendendo gli orecchi, attenti a lontani suoni di tromba.



## Coscienza {-}

Venne una guerra e un certo Luigi chiese se poteva andarci, da volontario.

Tutti gli fecero un sacco di complimenti. Luigi andò nel posto dove davano i fucili, ne prese uno e disse: – Adesso vado a ammazzare un certo Alberto.

Gli chiesero chi era questo Alberto.

– Un nemico – rispose, – un nemico che ci ho io.

Quelli gli fecero capire che doveva ammazzare dei nemici di una data qualità, non quelli che piacevano a lui.

– E che? – disse Luigi – Mi pigliate per ignorante? Quel tale Alberto è proprio di quella qualità, di quel paese. Quando ho saputo che ci facevate la guerra contro, ho pensato: vengo anch’io, così posso ammazzare Alberto. Per questo son venuto. Alberto io lo conosco: è un farabutto e per pochi soldi mi ha fatto fare una brutta parte davanti a una. Sono faccende vecchie. Se non ci credete, vi racconto tutto per disteso.

Loro dissero che sì, che andava bene.

– Allora – fece Luigi – mi spiegate dov’è Alberto, così ci vado e ci combatto.

Loro dissero che non ne sapevano.

– Non importa – disse Luigi, – mi farò spiegare. Prima o poi lo troverò bene.

Quelli gli dissero che non si poteva, che lui doveva fare la guerra dove lo mettevan loro, e ammazzare chi capitava, di Alberto o non Alberto loro non sapevano niente.

– Vedete – insisteva Luigi – bisogna proprio che vi racconti. Perché quello è proprio un farabutto e fate bene a farci la guerra contro.

Ma gli altri non ne volevano sapere.

Luigi non riusciva a farsi ragione: – Scusate, per voi se ammazzo un nemico o se ne ammazzo un altro è lo stesso. A me invece di ammazzare qualcuno che magari con Alberto non ha niente a che vedere, dispiace.

Gli altri persero la pazienza. Qualcuno gli spiegò di tante ragioni e di come era fatta la guerra e che uno non poteva andarsi a cercare il nemico che voleva.

Luigi alzò le spalle. – Se è così – disse – io non ci sto.

– Ci sei e ci stai! – gridarono quelli.

– Avanti-march, un-duè, un-duè! – E lo mandarono a far la guerra.

Luigi non era contento. Ammazzava dei nemici, così, per vedere se gli capitava di ammazzare anche Alberto o qualche suo parente. Gli davano una medaglia ogni nemico che ammazzava, ma lui non era contento. – Se non ammazzo Alberto – pensava – ho ammazzato tanta gente per niente. – E ne aveva rimorso.

Intanto gli davano medaglie su medaglie, di tutti i metalli.

Luigi pensava: – Ammazza oggi ammazza domani, i nemici diminuiranno e verrà pure la volta di quel farabutto.

Ma i nemici si arresero prima che Luigi avesse trovato Alberto. Gli venne il rimorso di aver ammazzato tanta gente per niente, e siccome c’era la pace, mise tutte le medaglie in un sacco e girò per il paese dei nemici a regalarle ai figli e alle mogli dei morti.

Girando così, successe che trovò Alberto.

– Bene – disse – meglio tardi che mai – e lo ammazzò.

Fu la volta che lo arrestarono, lo processarono per omicidio e lo impiccarono. Al processo badava a ripetere che l’aveva fatto per mettersi a posto con la coscienza, ma nessuno lo stava a sentire.




## Solidarietà {-}

Mi fermai a guardarli.

Lavoravano così, di notte, in quella via appartata, intorno alla saracinesca di un negozio.

Era una saracinesca pesante: loro facevano leva con un palo di ferro ma quella non si alzava.

Passavo di lì, solo e per caso. Mi attaccai anch’io al palo a far forza. Loro mi fecero posto.

Non s’andava bene a tempo; io feci «Ooh-op!» Il compagno di destra mi diede una gomitata e, piano: «Zitto! – mi disse – sei matto! Vuoi che ci sentano?»

Io scossi il capo come a dire che mi era sfuggito.

Ci mettemmo un po’ e sudammo ma alla fine l’alzammo tanto che si poteva passarci. Ci si guardò in faccia, contenti. Poi s’entrò. A me diedero da tenere un sacco. Gli altri portavano roba e la mettevano dentro.

«Purché non arrivino quei vigliacchi della polizia!» dicevano.

– Davvero – rispondevo io. – Vigliacchi che non sono altro! – Zitto. Non senti rumore di passi? – facevano ogni tanto. Io tendevo le orecchie con un po’ di paura. – Ma no, non sono loro! – rispondevo.

– Quelli arrivano sempre quando meno ce li si aspetta! – mi faceva uno.

Io scuotevo il capo. – Ammazzarli tutti, si dovrebbe – dicevo.

Poi mi dissero di andare un po’ fuori, alla svolta, a vedere se arrivava nessuno. Io andai.

Fuori, alla svolta, c’erano degli altri rasenti ai muri, nascosti negli angoli, che venivano avanti.

Mi ci misi anch’io.

– Dei rumori laggiù, verso quei negozi – disse quello che mi era vicino.

Io feci capolino.

– Metti la testa dentro, imbecille, che se ci vedono ci scappano un’altra volta – bisbigliò.

– Guardavo… – mi scusai e m’acquattai al muro.

– Se ci riesce di aggirarli senza che se ne accorgano – fece un altro – li prendiamo in trappola tanti quanti sono.

Ci muovevamo a balzi, in punta di piedi, trattenendo il respiro: ogni poco ci guardavamo l’un l’altro, con gli occhi lustri.

– Non ci scappano più – dissi.

– Finalmente riusciremo a coglierli con le mani nel sacco – fece uno.

– Era ora – dissi io.

– Cani di delinquenti, svaligiare così i negozi! – disse quello.

– Cani, cani! – ripetei io, con rabbia.

Mi mandarono un po’ avanti, a vedere. Capitai dentro il negozio.

– Ormai – diceva uno mettendo in ispalla un sacco – non ci pigliano più.

– Svelti – disse un altro – tagliamo via dal retrobottega! Così gli scappiamo di sotto al naso.

Avevamo tutti un sorriso di trionfo sulle labbra. – Resteranno con un bel palmo di naso – dissi. E si sgattaiolò nel retrobottega.

– Ancora una volta che li giochiamo come merli! – dicevano. Su quella si sentì: – Alto là, chi va là – e le luci si accesero. Noi ci acquattammo dietro un nascondiglio, pallidi, e ci prendemmo per mano. Quelli entrarono anche lì, non ci videro, girarono. Noi schizzammo fuori e via a gambe levate. – Glie l’abbiamo fatta! – gridammo. Io inciampai due o tre volte e rimasi indietro. Mi trovai in mezzo agli altri che correvano pure.

– Dai – mi dissero – che li raggiungiamo.

E tutti si galoppava pei vicoli, inseguendo. – Corri di qui, taglia di là – ci si diceva e quelli ci avanzavano ormai di poco, e si gridava: – Dai che non ci scappano.

Io riuscii a mettermi alle calcagna di uno. Quello mi disse: – Bravo, sei riuscito a scappare. Forza, da questa parte, che facciamo perdere le tracce! – e io mi accodai a lui. Dopo un po’ mi trovai solo, in un vicolo. Uno mi scantonò vicino, mi disse correndo: «Dai, da questa parte, li ho visti io, non possono essersi allontanati». Io corsi un po’ dietro a lui.

Poi mi fermai, sudato. Non c’era più nessuno, non si sentivano più grida. Rimasi con le mani in tasca e ripresi a passeggiare, solo e a caso.