# Il signor Veneranda {-}

di Carlo Manzoni (Milano, Rizzoli, 1949)

## La chiave {-}

Il signor Veneranda si fermò davanti al portone di una casa, guardò le finestre buie e spente e fischiò più volte come volesse chiamare qualcuno. A una finestra del terzo piano si affacciò un signore.

- È senza chiave? - chiese il signore gridando per farsi sentire.

- Si, sono senza chiave - gridò il signor Veneranda.

- E il portone è chiuso? - gridò di nuovo il signore affacciato.

- Si è chiuso - rispose il signor Veneranda.

- Allora le butto la chiave.

- Per fare cosa? - chiese il signor Veneranda.

- Per aprire il portone - rispose il signore affacciato.

- Va bene, - gridò il signor Veneranda - se vuole che apra il portone, butti pure la chiave.

- Ma lei deve entrare?

- Io no. Cosa dovrei entrare per fare?

- Ma non abita qui lei? - chiese il signore affacciato, che cominciava a non capire.

- Io no - gridò il signor Veneranda.

- E allora perché vuole la chiave?

- Se lei vuole che apra il portone non posso mica aprirlo con la pipa, le pare?

- Io non voglio aprire il portone, - gridò il signore affacciato - io credevo che lei abitasse qui: ho sentito che fischiava.

- Perché, tutti quelli che abitano in questa casa fischiano? - chiese il signor Veneranda, sempre gridando.

- Se sono senza chiave si! - rispose il signore affacciato.

- Io sono senza chiave - gridò il signor Veneranda.

- Insomma si può sapere cosa avete da gridare? Qui non si può dormire - urlò un signore affacciandosi a una finestra del primo piano.

- Gridiamo perché quello sta al terzo piano e io sto in strada - disse il signor Veneranda - se parliamo piano non ci si capisce.

- Ma lei cosa vuole? - chiese il signore affacciato al primo piano.

- Lo domandi a quello del terzo piano cosa vuole, - disse il signor Veneranda - io non ho ancora capito: prima vuol buttarmi la chiave per aprire il portone, poi non vuole che io apra il portone, poi dice che se fischio debbo abitare in questa casa. Insomma io non ho ancora capito. Lei fischia?

- Io? Io no... perché dovrei fischiare? - chiese il signore affacciato al primo piano.

- Perché abita in questa casa - disse il signor Veneranda -; l'ha detto quello del terzo piano che quelli che abitano in questa casa fischiano! Be', ad ogni modo non mi interessa, se vuole può anche fischiare.

Il signor Veneranda salutò con un cenno del capo e si avviò per la strada, brontolando che quello doveva essere una specie di manicomio.



## La macchia {-}

Il signor Veneranda si fermò sul pianerottolo delle scale, mise un dito su una macchia del muro accanto a una porta e si mise a premere con tutta la forza. Un signore si fermò a guardarlo. 

– Scusate –, disse il signore indicando la macchiolina sul muro – quella non è un campanello, è una macchia sul muro e non suona.

– Ah– disse il signor Veneranda. – non suona? E perchè dovrebbe suonare secondo voi? Io non ho mai visto delle macchie che suonano nemmeno a premerle. Sono i campanelli che suonano quando si premono.

– Appunto – disse il signore. – E quello non è un campanello, è una macchia sul muro.

– Appunto – disse il signor Veneranda. – E chi ha mai detto che questo è un campanello? Se fosse un campanello non premerei col dito. Perchè dovrei premere col dito su un campanello?

– Ma... voi non dovete suonare il campanello?

– Io no – disse il signor Veneranda. – Se dovessi suonare il campanello vi pare che premerei col dito su una macchia qualsiasi? Ma voi siete matto. Se volessi suonare il campanello premerei sul campanello. Voi dove premereste? Sulle macchie?

– Io no...– balbettò il signore che non sapeva cosa dire. – Io non... ma si può sapere perchè premete sulla macchia?

– Io non, e si può sapere e una cosa e l'altra – gridò il signor Veneranda perdendo la pazienza. – Ma sapete che siete un bel tipo? Se volete suonare il campanello suonatelo pure, io già non ho nessuna intenzione di suonare i campanelli.

E il signor Veneranda alzò le spalle poi scese le scale brontolando.
